25-Oct-2019 15:56:06.167 WARNING [Thread-389] org.apache.catalina.servlets.CGIServlet$CGIRunner.sendToLog stderr line: [Traceback (most recent call last):]
25-Oct-2019 15:56:06.168 WARNING [Thread-389] org.apache.catalina.servlets.CGIServlet$CGIRunner.sendToLog stderr line: [  File "C:\Users\hayde\Desktop\UCI\Fall 2019\EECS 118\MP2\apache-tomcat-9.0.26\webapps\test\WEB-INF\cgi\project_3_uploaded.py", line 13, in <module>]
25-Oct-2019 15:56:06.168 WARNING [Thread-389] org.apache.catalina.servlets.CGIServlet$CGIRunner.sendToLog stderr line: [    query = "select gallery_id from gallery where name='"+gallery_name+"'"]
25-Oct-2019 15:56:06.169 WARNING [Thread-389] org.apache.catalina.servlets.CGIServlet$CGIRunner.sendToLog stderr line: [TypeError: must be str, not NoneType]
25-Oct-2019 15:56:06.178 WARNING [Thread-389] org.apache.catalina.servlets.CGIServlet$CGIRunner.sendToLog Received [4] lines on stderr
25-Oct-2019 15:56:46.145 WARNING [Thread-390] org.apache.catalina.servlets.CGIServlet$CGIRunner.sendToLog stderr line: [Traceback (most recent call last):]
25-Oct-2019 15:56:46.145 WARNING [Thread-390] org.apache.catalina.servlets.CGIServlet$CGIRunner.sendToLog stderr line: [  File "C:\Users\hayde\Desktop\UCI\Fall 2019\EECS 118\MP2\apache-tomcat-9.0.26\webapps\test\WEB-INF\cgi\project_3_uploaded.py", line 13, in <module>]
25-Oct-2019 15:56:46.146 WARNING [Thread-390] org.apache.catalina.servlets.CGIServlet$CGIRunner.sendToLog stderr line: [    query = "select gallery_id from gallery where name='"+gallery_name+"'"]
25-Oct-2019 15:56:46.146 WARNING [Thread-390] org.apache.catalina.servlets.CGIServlet$CGIRunner.sendToLog stderr line: [TypeError: must be str, not NoneType]
25-Oct-2019 15:56:46.154 WARNING [Thread-390] org.apache.catalina.servlets.CGIServlet$CGIRunner.sendToLog Received [4] lines on stderr
25-Oct-2019 15:56:53.278 WARNING [Thread-391] org.apache.catalina.servlets.CGIServlet$CGIRunner.sendToLog stderr line: [Traceback (most recent call last):]
25-Oct-2019 15:56:53.279 WARNING [Thread-391] org.apache.catalina.servlets.CGIServlet$CGIRunner.sendToLog stderr line: [  File "C:\Users\hayde\Desktop\UCI\Fall 2019\EECS 118\MP2\apache-tomcat-9.0.26\webapps\test\WEB-INF\cgi\project_3_uploaded.py", line 13, in <module>]
25-Oct-2019 15:56:53.280 WARNING [Thread-391] org.apache.catalina.servlets.CGIServlet$CGIRunner.sendToLog stderr line: [    query = "select gallery_id from gallery where name='"+gallery_name+"'"]
25-Oct-2019 15:56:53.280 WARNING [Thread-391] org.apache.catalina.servlets.CGIServlet$CGIRunner.sendToLog stderr line: [TypeError: must be str, not NoneType]
25-Oct-2019 15:56:53.287 WARNING [Thread-391] org.apache.catalina.servlets.CGIServlet$CGIRunner.sendToLog Received [4] lines on stderr
25-Oct-2019 15:57:37.196 WARNING [Thread-394] org.apache.catalina.servlets.CGIServlet$CGIRunner.sendToLog stderr line: [Traceback (most recent call last):]
25-Oct-2019 15:57:37.196 WARNING [Thread-394] org.apache.catalina.servlets.CGIServlet$CGIRunner.sendToLog stderr line: [  File "C:\Users\hayde\Desktop\UCI\Fall 2019\EECS 118\MP2\apache-tomcat-9.0.26\webapps\test\WEB-INF\cgi\project_3_gallery1.py", line 44, in <module>]
25-Oct-2019 15:57:37.197 WARNING [Thread-394] org.apache.catalina.servlets.CGIServlet$CGIRunner.sendToLog stderr line: [    query = "select gallery_id from gallery where name='"+gal+"'"]
25-Oct-2019 15:57:37.197 WARNING [Thread-394] org.apache.catalina.servlets.CGIServlet$CGIRunner.sendToLog stderr line: [TypeError: must be str, not NoneType]
25-Oct-2019 15:57:37.204 WARNING [Thread-394] org.apache.catalina.servlets.CGIServlet$CGIRunner.sendToLog Received [4] lines on stderr
25-Oct-2019 15:58:36.317 WARNING [Thread-396] org.apache.catalina.servlets.CGIServlet$CGIRunner.sendToLog stderr line: [Traceback (most recent call last):]
25-Oct-2019 15:58:36.317 WARNING [Thread-396] org.apache.catalina.servlets.CGIServlet$CGIRunner.sendToLog stderr line: [  File "C:\Users\hayde\Desktop\UCI\Fall 2019\EECS 118\MP2\apache-tomcat-9.0.26\webapps\test\WEB-INF\cgi\project_3_gallery1.py", line 49, in <module>]
25-Oct-2019 15:58:36.318 WARNING [Thread-396] org.apache.catalina.servlets.CGIServlet$CGIRunner.sendToLog stderr line: [    query = "select*from image where gallery_id ='"+str(gal_id[0])+"'"]
25-Oct-2019 15:58:36.318 WARNING [Thread-396] org.apache.catalina.servlets.CGIServlet$CGIRunner.sendToLog stderr line: [TypeError: 'NoneType' object is not subscriptable]
25-Oct-2019 15:58:36.326 WARNING [Thread-396] org.apache.catalina.servlets.CGIServlet$CGIRunner.sendToLog Received [4] lines on stderr
25-Oct-2019 15:59:02.032 WARNING [Thread-398] org.apache.catalina.servlets.CGIServlet$CGIRunner.sendToLog stderr line: [Traceback (most recent call last):]
25-Oct-2019 15:59:02.032 WARNING [Thread-398] org.apache.catalina.servlets.CGIServlet$CGIRunner.sendToLog stderr line: [  File "C:\Users\hayde\Desktop\UCI\Fall 2019\EECS 118\MP2\apache-tomcat-9.0.26\webapps\test\WEB-INF\cgi\project_3_gallery1.py", line 49, in <module>]
25-Oct-2019 15:59:02.033 WARNING [Thread-398] org.apache.catalina.servlets.CGIServlet$CGIRunner.sendToLog stderr line: [    query = "select*from image where gallery_id ='"+str(gal_id[0])+"'"]
25-Oct-2019 15:59:02.033 WARNING [Thread-398] org.apache.catalina.servlets.CGIServlet$CGIRunner.sendToLog stderr line: [TypeError: 'NoneType' object is not subscriptable]
25-Oct-2019 15:59:02.040 WARNING [Thread-398] org.apache.catalina.servlets.CGIServlet$CGIRunner.sendToLog Received [4] lines on stderr
25-Oct-2019 15:59:17.640 WARNING [Thread-399] org.apache.catalina.servlets.CGIServlet$CGIRunner.sendToLog stderr line: [Traceback (most recent call last):]
25-Oct-2019 15:59:17.640 WARNING [Thread-399] org.apache.catalina.servlets.CGIServlet$CGIRunner.sendToLog stderr line: [  File "C:\Users\hayde\Desktop\UCI\Fall 2019\EECS 118\MP2\apache-tomcat-9.0.26\webapps\test\WEB-INF\cgi\project_3_gallery1.py", line 49, in <module>]
25-Oct-2019 15:59:17.640 WARNING [Thread-399] org.apache.catalina.servlets.CGIServlet$CGIRunner.sendToLog stderr line: [    query = "select*from image where gallery_id ='"+str(gal_id[0])+"'"]
25-Oct-2019 15:59:17.640 WARNING [Thread-399] org.apache.catalina.servlets.CGIServlet$CGIRunner.sendToLog stderr line: [TypeError: 'NoneType' object is not subscriptable]
25-Oct-2019 15:59:17.648 WARNING [Thread-399] org.apache.catalina.servlets.CGIServlet$CGIRunner.sendToLog Received [4] lines on stderr
25-Oct-2019 15:59:20.528 WARNING [Thread-400] org.apache.catalina.servlets.CGIServlet$CGIRunner.sendToLog stderr line: [Traceback (most recent call last):]
25-Oct-2019 15:59:20.528 WARNING [Thread-400] org.apache.catalina.servlets.CGIServlet$CGIRunner.sendToLog stderr line: [  File "C:\Users\hayde\Desktop\UCI\Fall 2019\EECS 118\MP2\apache-tomcat-9.0.26\webapps\test\WEB-INF\cgi\project_3_gallery1.py", line 49, in <module>]
25-Oct-2019 15:59:20.528 WARNING [Thread-400] org.apache.catalina.servlets.CGIServlet$CGIRunner.sendToLog stderr line: [    query = "select*from image where gallery_id ='"+str(gal_id[0])+"'"]
25-Oct-2019 15:59:20.529 WARNING [Thread-400] org.apache.catalina.servlets.CGIServlet$CGIRunner.sendToLog stderr line: [TypeError: 'NoneType' object is not subscriptable]
25-Oct-2019 15:59:20.536 WARNING [Thread-400] org.apache.catalina.servlets.CGIServlet$CGIRunner.sendToLog Received [4] lines on stderr
25-Oct-2019 16:00:14.329 WARNING [Thread-401] org.apache.catalina.servlets.CGIServlet$CGIRunner.sendToLog stderr line: [Traceback (most recent call last):]
25-Oct-2019 16:00:14.329 WARNING [Thread-401] org.apache.catalina.servlets.CGIServlet$CGIRunner.sendToLog stderr line: [  File "C:\Users\hayde\Desktop\UCI\Fall 2019\EECS 118\MP2\apache-tomcat-9.0.26\webapps\test\WEB-INF\cgi\project_3_gallery1.py", line 49, in <module>]
25-Oct-2019 16:00:14.329 WARNING [Thread-401] org.apache.catalina.servlets.CGIServlet$CGIRunner.sendToLog stderr line: [    query = "select*from image where gallery_id ='"+str(gal_id[0])+"'"]
25-Oct-2019 16:00:14.330 WARNING [Thread-401] org.apache.catalina.servlets.CGIServlet$CGIRunner.sendToLog stderr line: [TypeError: 'NoneType' object is not subscriptable]
25-Oct-2019 16:00:14.337 WARNING [Thread-401] org.apache.catalina.servlets.CGIServlet$CGIRunner.sendToLog Received [4] lines on stderr
25-Oct-2019 16:02:17.618 WARNING [Thread-406] org.apache.catalina.servlets.CGIServlet$CGIRunner.sendToLog stderr line: [Traceback (most recent call last):]
25-Oct-2019 16:02:17.619 WARNING [Thread-406] org.apache.catalina.servlets.CGIServlet$CGIRunner.sendToLog stderr line: [  File "C:\Users\hayde\Desktop\UCI\Fall 2019\EECS 118\MP2\apache-tomcat-9.0.26\webapps\test\WEB-INF\cgi\project_3_uploaded.py", line 13, in <module>]
25-Oct-2019 16:02:17.619 WARNING [Thread-406] org.apache.catalina.servlets.CGIServlet$CGIRunner.sendToLog stderr line: [    query = "select gallery_id from gallery where name='"+gallery_name+"'"]
25-Oct-2019 16:02:17.619 WARNING [Thread-406] org.apache.catalina.servlets.CGIServlet$CGIRunner.sendToLog stderr line: [TypeError: must be str, not NoneType]
25-Oct-2019 16:02:17.627 WARNING [Thread-406] org.apache.catalina.servlets.CGIServlet$CGIRunner.sendToLog Received [4] lines on stderr
25-Oct-2019 16:35:58.365 WARNING [Thread-428] org.apache.catalina.servlets.CGIServlet$CGIRunner.sendToLog stderr line: [Traceback (most recent call last):]
25-Oct-2019 16:35:58.365 WARNING [Thread-428] org.apache.catalina.servlets.CGIServlet$CGIRunner.sendToLog stderr line: [  File "C:\Users\hayde\Desktop\UCI\Fall 2019\EECS 118\MP2\apache-tomcat-9.0.26\webapps\test\WEB-INF\cgi\project_3.py", line 47, in <module>]
25-Oct-2019 16:35:58.366 WARNING [Thread-428] org.apache.catalina.servlets.CGIServlet$CGIRunner.sendToLog stderr line: [    print(js)]
25-Oct-2019 16:35:58.366 WARNING [Thread-428] org.apache.catalina.servlets.CGIServlet$CGIRunner.sendToLog stderr line: [NameError: name 'js' is not defined]
25-Oct-2019 16:35:58.374 WARNING [Thread-428] org.apache.catalina.servlets.CGIServlet$CGIRunner.sendToLog Received [4] lines on stderr
25-Oct-2019 16:36:28.757 WARNING [Thread-429] org.apache.catalina.servlets.CGIServlet$CGIRunner.sendToLog stderr line: [Traceback (most recent call last):]
25-Oct-2019 16:36:28.757 WARNING [Thread-429] org.apache.catalina.servlets.CGIServlet$CGIRunner.sendToLog stderr line: [  File "C:\Users\hayde\Desktop\UCI\Fall 2019\EECS 118\MP2\apache-tomcat-9.0.26\webapps\test\WEB-INF\cgi\project_3.py", line 47, in <module>]
25-Oct-2019 16:36:28.758 WARNING [Thread-429] org.apache.catalina.servlets.CGIServlet$CGIRunner.sendToLog stderr line: [    print(js)]
25-Oct-2019 16:36:28.759 WARNING [Thread-429] org.apache.catalina.servlets.CGIServlet$CGIRunner.sendToLog stderr line: [NameError: name 'js' is not defined]
25-Oct-2019 16:36:28.768 WARNING [Thread-429] org.apache.catalina.servlets.CGIServlet$CGIRunner.sendToLog Received [4] lines on stderr
25-Oct-2019 16:36:36.944 WARNING [Thread-430] org.apache.catalina.servlets.CGIServlet$CGIRunner.sendToLog stderr line: [Traceback (most recent call last):]
25-Oct-2019 16:36:36.944 WARNING [Thread-430] org.apache.catalina.servlets.CGIServlet$CGIRunner.sendToLog stderr line: [  File "C:\Users\hayde\Desktop\UCI\Fall 2019\EECS 118\MP2\apache-tomcat-9.0.26\webapps\test\WEB-INF\cgi\project_3.py", line 46, in <module>]
25-Oct-2019 16:36:36.945 WARNING [Thread-430] org.apache.catalina.servlets.CGIServlet$CGIRunner.sendToLog stderr line: [    print(js)]
25-Oct-2019 16:36:36.945 WARNING [Thread-430] org.apache.catalina.servlets.CGIServlet$CGIRunner.sendToLog stderr line: [NameError: name 'js' is not defined]
25-Oct-2019 16:36:36.953 WARNING [Thread-430] org.apache.catalina.servlets.CGIServlet$CGIRunner.sendToLog Received [4] lines on stderr
25-Oct-2019 16:38:49.462 WARNING [Thread-431] org.apache.catalina.servlets.CGIServlet$CGIRunner.sendToLog stderr line: [Traceback (most recent call last):]
25-Oct-2019 16:38:49.462 WARNING [Thread-431] org.apache.catalina.servlets.CGIServlet$CGIRunner.sendToLog stderr line: [  File "C:\Users\hayde\Desktop\UCI\Fall 2019\EECS 118\MP2\apache-tomcat-9.0.26\webapps\test\WEB-INF\cgi\project_3.py", line 47, in <module>]
25-Oct-2019 16:38:49.462 WARNING [Thread-431] org.apache.catalina.servlets.CGIServlet$CGIRunner.sendToLog stderr line: [    print(js)]
25-Oct-2019 16:38:49.463 WARNING [Thread-431] org.apache.catalina.servlets.CGIServlet$CGIRunner.sendToLog stderr line: [NameError: name 'js' is not defined]
25-Oct-2019 16:38:49.470 WARNING [Thread-431] org.apache.catalina.servlets.CGIServlet$CGIRunner.sendToLog Received [4] lines on stderr
25-Oct-2019 16:43:59.625 WARNING [Thread-433] org.apache.catalina.servlets.CGIServlet$CGIRunner.sendToLog stderr line: [  File "C:\Users\hayde\Desktop\UCI\Fall 2019\EECS 118\MP2\apache-tomcat-9.0.26\webapps\test\WEB-INF\cgi\project_3_gal_upload.py", line 20]
25-Oct-2019 16:43:59.626 WARNING [Thread-433] org.apache.catalina.servlets.CGIServlet$CGIRunner.sendToLog stderr line: [    ]
25-Oct-2019 16:43:59.626 WARNING [Thread-433] org.apache.catalina.servlets.CGIServlet$CGIRunner.sendToLog stderr line: [     ^]
25-Oct-2019 16:43:59.626 WARNING [Thread-433] org.apache.catalina.servlets.CGIServlet$CGIRunner.sendToLog stderr line: [SyntaxError: unexpected EOF while parsing]
25-Oct-2019 16:43:59.628 WARNING [Thread-433] org.apache.catalina.servlets.CGIServlet$CGIRunner.sendToLog Received [4] lines on stderr
25-Oct-2019 16:44:17.577 WARNING [Thread-434] org.apache.catalina.servlets.CGIServlet$CGIRunner.sendToLog stderr line: [  File "C:\Users\hayde\Desktop\UCI\Fall 2019\EECS 118\MP2\apache-tomcat-9.0.26\webapps\test\WEB-INF\cgi\project_3_gal_upload.py", line 20]
25-Oct-2019 16:44:17.577 WARNING [Thread-434] org.apache.catalina.servlets.CGIServlet$CGIRunner.sendToLog stderr line: [    ]
25-Oct-2019 16:44:17.578 WARNING [Thread-434] org.apache.catalina.servlets.CGIServlet$CGIRunner.sendToLog stderr line: [     ^]
25-Oct-2019 16:44:17.578 WARNING [Thread-434] org.apache.catalina.servlets.CGIServlet$CGIRunner.sendToLog stderr line: [SyntaxError: unexpected EOF while parsing]
25-Oct-2019 16:44:17.580 WARNING [Thread-434] org.apache.catalina.servlets.CGIServlet$CGIRunner.sendToLog Received [4] lines on stderr
25-Oct-2019 16:47:46.794 WARNING [Thread-437] org.apache.catalina.servlets.CGIServlet$CGIRunner.sendToLog stderr line: [  File "C:\Users\hayde\Desktop\UCI\Fall 2019\EECS 118\MP2\apache-tomcat-9.0.26\webapps\test\WEB-INF\cgi\project_3_gal_upload.py", line 21]
25-Oct-2019 16:47:46.794 WARNING [Thread-437] org.apache.catalina.servlets.CGIServlet$CGIRunner.sendToLog stderr line: [    val = (str(form.getvalue('gal_name')), str(form.getvalue('description')))]
25-Oct-2019 16:47:46.795 WARNING [Thread-437] org.apache.catalina.servlets.CGIServlet$CGIRunner.sendToLog stderr line: [                                                                            ^]
25-Oct-2019 16:47:46.795 WARNING [Thread-437] org.apache.catalina.servlets.CGIServlet$CGIRunner.sendToLog stderr line: [IndentationError: unindent does not match any outer indentation level]
25-Oct-2019 16:47:46.797 WARNING [Thread-437] org.apache.catalina.servlets.CGIServlet$CGIRunner.sendToLog Received [4] lines on stderr
25-Oct-2019 16:48:05.280 WARNING [Thread-438] org.apache.catalina.servlets.CGIServlet$CGIRunner.sendToLog stderr line: [  File "C:\Users\hayde\Desktop\UCI\Fall 2019\EECS 118\MP2\apache-tomcat-9.0.26\webapps\test\WEB-INF\cgi\project_3_gal_upload.py", line 21]
25-Oct-2019 16:48:05.280 WARNING [Thread-438] org.apache.catalina.servlets.CGIServlet$CGIRunner.sendToLog stderr line: [    val = (str(form.getvalue('gal_name')), str(form.getvalue('description')))]
25-Oct-2019 16:48:05.280 WARNING [Thread-438] org.apache.catalina.servlets.CGIServlet$CGIRunner.sendToLog stderr line: [                                                                            ^]
25-Oct-2019 16:48:05.281 WARNING [Thread-438] org.apache.catalina.servlets.CGIServlet$CGIRunner.sendToLog stderr line: [IndentationError: unindent does not match any outer indentation level]
25-Oct-2019 16:48:05.283 WARNING [Thread-438] org.apache.catalina.servlets.CGIServlet$CGIRunner.sendToLog Received [4] lines on stderr
25-Oct-2019 16:48:33.449 WARNING [Thread-439] org.apache.catalina.servlets.CGIServlet$CGIRunner.sendToLog stderr line: [  File "C:\Users\hayde\Desktop\UCI\Fall 2019\EECS 118\MP2\apache-tomcat-9.0.26\webapps\test\WEB-INF\cgi\project_3_gal_upload.py", line 21]
25-Oct-2019 16:48:33.449 WARNING [Thread-439] org.apache.catalina.servlets.CGIServlet$CGIRunner.sendToLog stderr line: [    val = (str(form.getvalue('gal_name')), str(form.getvalue('description')))]
25-Oct-2019 16:48:33.450 WARNING [Thread-439] org.apache.catalina.servlets.CGIServlet$CGIRunner.sendToLog stderr line: [                                                                            ^]
25-Oct-2019 16:48:33.450 WARNING [Thread-439] org.apache.catalina.servlets.CGIServlet$CGIRunner.sendToLog stderr line: [IndentationError: unindent does not match any outer indentation level]
25-Oct-2019 16:48:33.452 WARNING [Thread-439] org.apache.catalina.servlets.CGIServlet$CGIRunner.sendToLog Received [4] lines on stderr
25-Oct-2019 16:50:02.339 WARNING [Thread-440] org.apache.catalina.servlets.CGIServlet$CGIRunner.sendToLog stderr line: [  File "C:\Users\hayde\Desktop\UCI\Fall 2019\EECS 118\MP2\apache-tomcat-9.0.26\webapps\test\WEB-INF\cgi\project_3_gal_upload.py", line 22]
25-Oct-2019 16:50:02.339 WARNING [Thread-440] org.apache.catalina.servlets.CGIServlet$CGIRunner.sendToLog stderr line: [    val = (str(form.getvalue('gal_name')), str(form.getvalue('description')))]
25-Oct-2019 16:50:02.340 WARNING [Thread-440] org.apache.catalina.servlets.CGIServlet$CGIRunner.sendToLog stderr line: [                                                                            ^]
25-Oct-2019 16:50:02.340 WARNING [Thread-440] org.apache.catalina.servlets.CGIServlet$CGIRunner.sendToLog stderr line: [IndentationError: unindent does not match any outer indentation level]
25-Oct-2019 16:50:02.342 WARNING [Thread-440] org.apache.catalina.servlets.CGIServlet$CGIRunner.sendToLog Received [4] lines on stderr
25-Oct-2019 16:51:48.561 WARNING [Thread-441] org.apache.catalina.servlets.CGIServlet$CGIRunner.sendToLog stderr line: [  File "C:\Users\hayde\Desktop\UCI\Fall 2019\EECS 118\MP2\apache-tomcat-9.0.26\webapps\test\WEB-INF\cgi\project_3_gal_upload.py", line 25]
25-Oct-2019 16:51:48.561 WARNING [Thread-441] org.apache.catalina.servlets.CGIServlet$CGIRunner.sendToLog stderr line: [    val = (str(form.getvalue('gal_name')), str(form.getvalue('description')))]
25-Oct-2019 16:51:48.562 WARNING [Thread-441] org.apache.catalina.servlets.CGIServlet$CGIRunner.sendToLog stderr line: [                                                                            ^]
25-Oct-2019 16:51:48.562 WARNING [Thread-441] org.apache.catalina.servlets.CGIServlet$CGIRunner.sendToLog stderr line: [IndentationError: unindent does not match any outer indentation level]
25-Oct-2019 16:51:48.564 WARNING [Thread-441] org.apache.catalina.servlets.CGIServlet$CGIRunner.sendToLog Received [4] lines on stderr
25-Oct-2019 16:53:56.838 WARNING [Thread-443] org.apache.catalina.servlets.CGIServlet$CGIRunner.sendToLog stderr line: [  File "C:\Users\hayde\Desktop\UCI\Fall 2019\EECS 118\MP2\apache-tomcat-9.0.26\webapps\test\WEB-INF\cgi\project_3_gal_upload.py", line 25]
25-Oct-2019 16:53:56.838 WARNING [Thread-443] org.apache.catalina.servlets.CGIServlet$CGIRunner.sendToLog stderr line: [    val = (str(form.getvalue('gal_name')), str(form.getvalue('description')))]
25-Oct-2019 16:53:56.839 WARNING [Thread-443] org.apache.catalina.servlets.CGIServlet$CGIRunner.sendToLog stderr line: [                                                                            ^]
25-Oct-2019 16:53:56.839 WARNING [Thread-443] org.apache.catalina.servlets.CGIServlet$CGIRunner.sendToLog stderr line: [IndentationError: unindent does not match any outer indentation level]
25-Oct-2019 16:53:56.841 WARNING [Thread-443] org.apache.catalina.servlets.CGIServlet$CGIRunner.sendToLog Received [4] lines on stderr
25-Oct-2019 16:54:00.790 WARNING [Thread-444] org.apache.catalina.servlets.CGIServlet$CGIRunner.sendToLog stderr line: [  File "C:\Users\hayde\Desktop\UCI\Fall 2019\EECS 118\MP2\apache-tomcat-9.0.26\webapps\test\WEB-INF\cgi\project_3_gal_upload.py", line 25]
25-Oct-2019 16:54:00.790 WARNING [Thread-444] org.apache.catalina.servlets.CGIServlet$CGIRunner.sendToLog stderr line: [    val = (str(form.getvalue('gal_name')), str(form.getvalue('description')))]
25-Oct-2019 16:54:00.791 WARNING [Thread-444] org.apache.catalina.servlets.CGIServlet$CGIRunner.sendToLog stderr line: [                                                                            ^]
25-Oct-2019 16:54:00.791 WARNING [Thread-444] org.apache.catalina.servlets.CGIServlet$CGIRunner.sendToLog stderr line: [IndentationError: unindent does not match any outer indentation level]
25-Oct-2019 16:54:00.793 WARNING [Thread-444] org.apache.catalina.servlets.CGIServlet$CGIRunner.sendToLog Received [4] lines on stderr
25-Oct-2019 17:00:29.824 WARNING [Thread-449] org.apache.catalina.servlets.CGIServlet$CGIRunner.sendToLog stderr line: [Traceback (most recent call last):]
25-Oct-2019 17:00:29.824 WARNING [Thread-449] org.apache.catalina.servlets.CGIServlet$CGIRunner.sendToLog stderr line: [  File "C:\Users\hayde\Desktop\UCI\Fall 2019\EECS 118\MP2\apache-tomcat-9.0.26\webapps\test\WEB-INF\cgi\project_3.py", line 47, in <module>]
25-Oct-2019 17:00:29.825 WARNING [Thread-449] org.apache.catalina.servlets.CGIServlet$CGIRunner.sendToLog stderr line: [    print(js)]
25-Oct-2019 17:00:29.825 WARNING [Thread-449] org.apache.catalina.servlets.CGIServlet$CGIRunner.sendToLog stderr line: [NameError: name 'js' is not defined]
25-Oct-2019 17:00:29.832 WARNING [Thread-449] org.apache.catalina.servlets.CGIServlet$CGIRunner.sendToLog Received [4] lines on stderr
25-Oct-2019 17:00:52.453 WARNING [Thread-453] org.apache.catalina.servlets.CGIServlet$CGIRunner.sendToLog stderr line: [Traceback (most recent call last):]
25-Oct-2019 17:00:52.453 WARNING [Thread-453] org.apache.catalina.servlets.CGIServlet$CGIRunner.sendToLog stderr line: [  File "C:\Users\hayde\Desktop\UCI\Fall 2019\EECS 118\MP2\apache-tomcat-9.0.26\webapps\test\WEB-INF\cgi\project_3.py", line 47, in <module>]
25-Oct-2019 17:00:52.454 WARNING [Thread-453] org.apache.catalina.servlets.CGIServlet$CGIRunner.sendToLog stderr line: [    print(js)]
25-Oct-2019 17:00:52.455 WARNING [Thread-453] org.apache.catalina.servlets.CGIServlet$CGIRunner.sendToLog stderr line: [NameError: name 'js' is not defined]
25-Oct-2019 17:00:52.466 WARNING [Thread-453] org.apache.catalina.servlets.CGIServlet$CGIRunner.sendToLog Received [4] lines on stderr
25-Oct-2019 17:01:57.661 WARNING [Thread-456] org.apache.catalina.servlets.CGIServlet$CGIRunner.sendToLog stderr line: [Traceback (most recent call last):]
25-Oct-2019 17:01:57.661 WARNING [Thread-456] org.apache.catalina.servlets.CGIServlet$CGIRunner.sendToLog stderr line: [  File "C:\Users\hayde\Desktop\UCI\Fall 2019\EECS 118\MP2\apache-tomcat-9.0.26\webapps\test\WEB-INF\cgi\project_3.py", line 47, in <module>]
25-Oct-2019 17:01:57.662 WARNING [Thread-456] org.apache.catalina.servlets.CGIServlet$CGIRunner.sendToLog stderr line: [    print(js)]
25-Oct-2019 17:01:57.662 WARNING [Thread-456] org.apache.catalina.servlets.CGIServlet$CGIRunner.sendToLog stderr line: [NameError: name 'js' is not defined]
25-Oct-2019 17:01:57.669 WARNING [Thread-456] org.apache.catalina.servlets.CGIServlet$CGIRunner.sendToLog Received [4] lines on stderr
25-Oct-2019 17:02:38.784 WARNING [Thread-459] org.apache.catalina.servlets.CGIServlet$CGIRunner.sendToLog stderr line: [Traceback (most recent call last):]
25-Oct-2019 17:02:38.784 WARNING [Thread-459] org.apache.catalina.servlets.CGIServlet$CGIRunner.sendToLog stderr line: [  File "C:\Users\hayde\Desktop\UCI\Fall 2019\EECS 118\MP2\apache-tomcat-9.0.26\webapps\test\WEB-INF\cgi\project_3.py", line 47, in <module>]
25-Oct-2019 17:02:38.785 WARNING [Thread-459] org.apache.catalina.servlets.CGIServlet$CGIRunner.sendToLog stderr line: [    print(js)]
25-Oct-2019 17:02:38.786 WARNING [Thread-459] org.apache.catalina.servlets.CGIServlet$CGIRunner.sendToLog stderr line: [NameError: name 'js' is not defined]
25-Oct-2019 17:02:38.793 WARNING [Thread-459] org.apache.catalina.servlets.CGIServlet$CGIRunner.sendToLog Received [4] lines on stderr
25-Oct-2019 17:07:36.525 WARNING [Thread-461] org.apache.catalina.servlets.CGIServlet$CGIRunner.sendToLog stderr line: [Traceback (most recent call last):]
25-Oct-2019 17:07:36.525 WARNING [Thread-461] org.apache.catalina.servlets.CGIServlet$CGIRunner.sendToLog stderr line: [  File "C:\Users\hayde\Desktop\UCI\Fall 2019\EECS 118\MP2\apache-tomcat-9.0.26\webapps\test\WEB-INF\cgi\project_3.py", line 47, in <module>]
25-Oct-2019 17:07:36.525 WARNING [Thread-461] org.apache.catalina.servlets.CGIServlet$CGIRunner.sendToLog stderr line: [    print(js)]
25-Oct-2019 17:07:36.526 WARNING [Thread-461] org.apache.catalina.servlets.CGIServlet$CGIRunner.sendToLog stderr line: [NameError: name 'js' is not defined]
25-Oct-2019 17:07:36.533 WARNING [Thread-461] org.apache.catalina.servlets.CGIServlet$CGIRunner.sendToLog Received [4] lines on stderr
25-Oct-2019 17:11:42.969 WARNING [Thread-468] org.apache.catalina.servlets.CGIServlet$CGIRunner.sendToLog stderr line: [Traceback (most recent call last):]
25-Oct-2019 17:11:42.969 WARNING [Thread-468] org.apache.catalina.servlets.CGIServlet$CGIRunner.sendToLog stderr line: [  File "C:\Users\hayde\Desktop\UCI\Fall 2019\EECS 118\MP2\apache-tomcat-9.0.26\webapps\test\WEB-INF\cgi\project_3.py", line 47, in <module>]
25-Oct-2019 17:11:42.969 WARNING [Thread-468] org.apache.catalina.servlets.CGIServlet$CGIRunner.sendToLog stderr line: [    print(js)]
25-Oct-2019 17:11:42.969 WARNING [Thread-468] org.apache.catalina.servlets.CGIServlet$CGIRunner.sendToLog stderr line: [NameError: name 'js' is not defined]
25-Oct-2019 17:11:42.979 WARNING [Thread-468] org.apache.catalina.servlets.CGIServlet$CGIRunner.sendToLog Received [4] lines on stderr
25-Oct-2019 17:36:30.360 WARNING [Thread-476] org.apache.catalina.servlets.CGIServlet$CGIRunner.sendToLog stderr line: [Traceback (most recent call last):]
25-Oct-2019 17:36:30.360 WARNING [Thread-476] org.apache.catalina.servlets.CGIServlet$CGIRunner.sendToLog stderr line: [  File "C:\Users\hayde\Desktop\UCI\Fall 2019\EECS 118\MP2\apache-tomcat-9.0.26\webapps\test\WEB-INF\cgi\project_3_del_img.py", line 18, in <module>]
25-Oct-2019 17:36:30.360 WARNING [Thread-476] org.apache.catalina.servlets.CGIServlet$CGIRunner.sendToLog stderr line: [    cur.execute(query, name)]
25-Oct-2019 17:36:30.361 WARNING [Thread-476] org.apache.catalina.servlets.CGIServlet$CGIRunner.sendToLog stderr line: [  File "C:\Users\hayde\AppData\Local\Programs\Python\Python36\lib\site-packages\pymysql\cursors.py", line 170, in execute]
25-Oct-2019 17:36:30.362 WARNING [Thread-476] org.apache.catalina.servlets.CGIServlet$CGIRunner.sendToLog stderr line: [    result = self._query(query)]
25-Oct-2019 17:36:30.362 WARNING [Thread-476] org.apache.catalina.servlets.CGIServlet$CGIRunner.sendToLog stderr line: [  File "C:\Users\hayde\AppData\Local\Programs\Python\Python36\lib\site-packages\pymysql\cursors.py", line 328, in _query]
25-Oct-2019 17:36:30.362 WARNING [Thread-476] org.apache.catalina.servlets.CGIServlet$CGIRunner.sendToLog stderr line: [    conn.query(q)]
25-Oct-2019 17:36:30.363 WARNING [Thread-476] org.apache.catalina.servlets.CGIServlet$CGIRunner.sendToLog stderr line: [  File "C:\Users\hayde\AppData\Local\Programs\Python\Python36\lib\site-packages\pymysql\connections.py", line 517, in query]
25-Oct-2019 17:36:30.363 WARNING [Thread-476] org.apache.catalina.servlets.CGIServlet$CGIRunner.sendToLog stderr line: [    self._affected_rows = self._read_query_result(unbuffered=unbuffered)]
25-Oct-2019 17:36:30.363 WARNING [Thread-476] org.apache.catalina.servlets.CGIServlet$CGIRunner.sendToLog stderr line: [  File "C:\Users\hayde\AppData\Local\Programs\Python\Python36\lib\site-packages\pymysql\connections.py", line 732, in _read_query_result]
25-Oct-2019 17:36:30.364 WARNING [Thread-476] org.apache.catalina.servlets.CGIServlet$CGIRunner.sendToLog stderr line: [    result.read()]
25-Oct-2019 17:36:30.364 WARNING [Thread-476] org.apache.catalina.servlets.CGIServlet$CGIRunner.sendToLog stderr line: [  File "C:\Users\hayde\AppData\Local\Programs\Python\Python36\lib\site-packages\pymysql\connections.py", line 1075, in read]
25-Oct-2019 17:36:30.364 WARNING [Thread-476] org.apache.catalina.servlets.CGIServlet$CGIRunner.sendToLog stderr line: [    first_packet = self.connection._read_packet()]
25-Oct-2019 17:36:30.364 WARNING [Thread-476] org.apache.catalina.servlets.CGIServlet$CGIRunner.sendToLog stderr line: [  File "C:\Users\hayde\AppData\Local\Programs\Python\Python36\lib\site-packages\pymysql\connections.py", line 684, in _read_packet]
25-Oct-2019 17:36:30.365 WARNING [Thread-476] org.apache.catalina.servlets.CGIServlet$CGIRunner.sendToLog stderr line: [    packet.check_error()]
25-Oct-2019 17:36:30.365 WARNING [Thread-476] org.apache.catalina.servlets.CGIServlet$CGIRunner.sendToLog stderr line: [  File "C:\Users\hayde\AppData\Local\Programs\Python\Python36\lib\site-packages\pymysql\protocol.py", line 220, in check_error]
25-Oct-2019 17:36:30.365 WARNING [Thread-476] org.apache.catalina.servlets.CGIServlet$CGIRunner.sendToLog stderr line: [    err.raise_mysql_exception(self._data)]
25-Oct-2019 17:36:30.365 WARNING [Thread-476] org.apache.catalina.servlets.CGIServlet$CGIRunner.sendToLog stderr line: [  File "C:\Users\hayde\AppData\Local\Programs\Python\Python36\lib\site-packages\pymysql\err.py", line 109, in raise_mysql_exception]
25-Oct-2019 17:36:30.366 WARNING [Thread-476] org.apache.catalina.servlets.CGIServlet$CGIRunner.sendToLog stderr line: [    raise errorclass(errno, errval)]
25-Oct-2019 17:36:30.366 WARNING [Thread-476] org.apache.catalina.servlets.CGIServlet$CGIRunner.sendToLog stderr line: [pymysql.err.InternalError: (1054, "Unknown column 'name' in 'where clause'")]
25-Oct-2019 17:36:30.370 WARNING [Thread-476] org.apache.catalina.servlets.CGIServlet$CGIRunner.sendToLog Received [20] lines on stderr
25-Oct-2019 17:38:07.696 WARNING [Thread-479] org.apache.catalina.servlets.CGIServlet$CGIRunner.sendToLog stderr line: [Traceback (most recent call last):]
25-Oct-2019 17:38:07.696 WARNING [Thread-479] org.apache.catalina.servlets.CGIServlet$CGIRunner.sendToLog stderr line: [  File "C:\Users\hayde\Desktop\UCI\Fall 2019\EECS 118\MP2\apache-tomcat-9.0.26\webapps\test\WEB-INF\cgi\project_3.py", line 47, in <module>]
25-Oct-2019 17:38:07.697 WARNING [Thread-479] org.apache.catalina.servlets.CGIServlet$CGIRunner.sendToLog stderr line: [    print(js)]
25-Oct-2019 17:38:07.697 WARNING [Thread-479] org.apache.catalina.servlets.CGIServlet$CGIRunner.sendToLog stderr line: [NameError: name 'js' is not defined]
25-Oct-2019 17:38:07.704 WARNING [Thread-479] org.apache.catalina.servlets.CGIServlet$CGIRunner.sendToLog Received [4] lines on stderr
25-Oct-2019 17:39:07.468 WARNING [Thread-486] org.apache.catalina.servlets.CGIServlet$CGIRunner.sendToLog stderr line: [Traceback (most recent call last):]
25-Oct-2019 17:39:07.469 WARNING [Thread-486] org.apache.catalina.servlets.CGIServlet$CGIRunner.sendToLog stderr line: [  File "C:\Users\hayde\Desktop\UCI\Fall 2019\EECS 118\MP2\apache-tomcat-9.0.26\webapps\test\WEB-INF\cgi\project_3.py", line 47, in <module>]
25-Oct-2019 17:39:07.469 WARNING [Thread-486] org.apache.catalina.servlets.CGIServlet$CGIRunner.sendToLog stderr line: [    print(js)]
25-Oct-2019 17:39:07.469 WARNING [Thread-486] org.apache.catalina.servlets.CGIServlet$CGIRunner.sendToLog stderr line: [NameError: name 'js' is not defined]
25-Oct-2019 17:39:07.476 WARNING [Thread-486] org.apache.catalina.servlets.CGIServlet$CGIRunner.sendToLog Received [4] lines on stderr
25-Oct-2019 17:55:24.141 WARNING [Thread-494] org.apache.catalina.servlets.CGIServlet$CGIRunner.sendToLog stderr line: [Traceback (most recent call last):]
25-Oct-2019 17:55:24.141 WARNING [Thread-494] org.apache.catalina.servlets.CGIServlet$CGIRunner.sendToLog stderr line: [  File "C:\Users\hayde\Desktop\UCI\Fall 2019\EECS 118\MP2\apache-tomcat-9.0.26\webapps\test\WEB-INF\cgi\project_3_artist_added.py", line 29, in <module>]
25-Oct-2019 17:55:24.141 WARNING [Thread-494] org.apache.catalina.servlets.CGIServlet$CGIRunner.sendToLog stderr line: [    display = "<form enctype='multipart/form-data' action='/test/cgi-bin/project_3_gallery1.py' method='POST'><input type='hidden' name='gal_name' value='"+gallery_name+"'><button type='submit'>Go Back</button></form>"]
25-Oct-2019 17:55:24.142 WARNING [Thread-494] org.apache.catalina.servlets.CGIServlet$CGIRunner.sendToLog stderr line: [TypeError: must be str, not NoneType]
25-Oct-2019 17:55:24.149 WARNING [Thread-494] org.apache.catalina.servlets.CGIServlet$CGIRunner.sendToLog Received [4] lines on stderr
25-Oct-2019 17:56:09.870 WARNING [Thread-496] org.apache.catalina.servlets.CGIServlet$CGIRunner.sendToLog stderr line: [Traceback (most recent call last):]
25-Oct-2019 17:56:09.871 WARNING [Thread-496] org.apache.catalina.servlets.CGIServlet$CGIRunner.sendToLog stderr line: [  File "C:\Users\hayde\Desktop\UCI\Fall 2019\EECS 118\MP2\apache-tomcat-9.0.26\webapps\test\WEB-INF\cgi\project_3_artist_added.py", line 29, in <module>]
25-Oct-2019 17:56:09.871 WARNING [Thread-496] org.apache.catalina.servlets.CGIServlet$CGIRunner.sendToLog stderr line: [    display = "<form enctype='multipart/form-data' action='/test/cgi-bin/project_3_gallery1.py' method='POST'><input type='hidden' name='gal_name' value='"+gallery_name+"'><button type='submit'>Go Back</button></form>"]
25-Oct-2019 17:56:09.872 WARNING [Thread-496] org.apache.catalina.servlets.CGIServlet$CGIRunner.sendToLog stderr line: [TypeError: must be str, not NoneType]
25-Oct-2019 17:56:09.879 WARNING [Thread-496] org.apache.catalina.servlets.CGIServlet$CGIRunner.sendToLog Received [4] lines on stderr
25-Oct-2019 18:01:46.503 WARNING [Thread-500] org.apache.catalina.servlets.CGIServlet$CGIRunner.sendToLog stderr line: [Traceback (most recent call last):]
25-Oct-2019 18:01:46.503 WARNING [Thread-500] org.apache.catalina.servlets.CGIServlet$CGIRunner.sendToLog stderr line: [  File "C:\Users\hayde\Desktop\UCI\Fall 2019\EECS 118\MP2\apache-tomcat-9.0.26\webapps\test\WEB-INF\cgi\project_3.py", line 47, in <module>]
25-Oct-2019 18:01:46.504 WARNING [Thread-500] org.apache.catalina.servlets.CGIServlet$CGIRunner.sendToLog stderr line: [    print(js)]
25-Oct-2019 18:01:46.504 WARNING [Thread-500] org.apache.catalina.servlets.CGIServlet$CGIRunner.sendToLog stderr line: [NameError: name 'js' is not defined]
25-Oct-2019 18:01:46.511 WARNING [Thread-500] org.apache.catalina.servlets.CGIServlet$CGIRunner.sendToLog Received [4] lines on stderr
25-Oct-2019 18:02:59.994 WARNING [Thread-505] org.apache.catalina.servlets.CGIServlet$CGIRunner.sendToLog stderr line: [Traceback (most recent call last):]
25-Oct-2019 18:02:59.994 WARNING [Thread-505] org.apache.catalina.servlets.CGIServlet$CGIRunner.sendToLog stderr line: [  File "C:\Users\hayde\Desktop\UCI\Fall 2019\EECS 118\MP2\apache-tomcat-9.0.26\webapps\test\WEB-INF\cgi\project_3.py", line 47, in <module>]
25-Oct-2019 18:02:59.995 WARNING [Thread-505] org.apache.catalina.servlets.CGIServlet$CGIRunner.sendToLog stderr line: [    print(js)]
25-Oct-2019 18:02:59.995 WARNING [Thread-505] org.apache.catalina.servlets.CGIServlet$CGIRunner.sendToLog stderr line: [NameError: name 'js' is not defined]
25-Oct-2019 18:03:00.003 WARNING [Thread-505] org.apache.catalina.servlets.CGIServlet$CGIRunner.sendToLog Received [4] lines on stderr
25-Oct-2019 18:03:47.332 WARNING [Thread-508] org.apache.catalina.servlets.CGIServlet$CGIRunner.sendToLog stderr line: [C:\Users\hayde\AppData\Local\Programs\Python\Python36\lib\site-packages\pymysql\cursors.py:170: Warning: (1366, "Incorrect integer value: '' for column 'year' at row 1")]
25-Oct-2019 18:03:47.333 WARNING [Thread-508] org.apache.catalina.servlets.CGIServlet$CGIRunner.sendToLog stderr line: [  result = self._query(query)]
25-Oct-2019 18:03:47.334 WARNING [Thread-508] org.apache.catalina.servlets.CGIServlet$CGIRunner.sendToLog stderr line: [C:\Users\hayde\AppData\Local\Programs\Python\Python36\lib\site-packages\pymysql\cursors.py:170: Warning: (1366, "Incorrect integer value: '' for column 'width' at row 1")]
25-Oct-2019 18:03:47.335 WARNING [Thread-508] org.apache.catalina.servlets.CGIServlet$CGIRunner.sendToLog stderr line: [  result = self._query(query)]
25-Oct-2019 18:03:47.336 WARNING [Thread-508] org.apache.catalina.servlets.CGIServlet$CGIRunner.sendToLog stderr line: [C:\Users\hayde\AppData\Local\Programs\Python\Python36\lib\site-packages\pymysql\cursors.py:170: Warning: (1366, "Incorrect integer value: '' for column 'height' at row 1")]
25-Oct-2019 18:03:47.336 WARNING [Thread-508] org.apache.catalina.servlets.CGIServlet$CGIRunner.sendToLog stderr line: [  result = self._query(query)]
25-Oct-2019 18:03:47.337 WARNING [Thread-508] org.apache.catalina.servlets.CGIServlet$CGIRunner.sendToLog stderr line: [Traceback (most recent call last):]
25-Oct-2019 18:03:47.338 WARNING [Thread-508] org.apache.catalina.servlets.CGIServlet$CGIRunner.sendToLog stderr line: [  File "C:\Users\hayde\Desktop\UCI\Fall 2019\EECS 118\MP2\apache-tomcat-9.0.26\webapps\test\WEB-INF\cgi\project_3_uploaded.py", line 33, in <module>]
25-Oct-2019 18:03:47.338 WARNING [Thread-508] org.apache.catalina.servlets.CGIServlet$CGIRunner.sendToLog stderr line: [    val = (form.getvalue('title'), form.getvalue('url'), str(id[0]), str(artist_id[0]), str(max_num_detail[0]))]
25-Oct-2019 18:03:47.339 WARNING [Thread-508] org.apache.catalina.servlets.CGIServlet$CGIRunner.sendToLog stderr line: [TypeError: 'NoneType' object is not subscriptable]
25-Oct-2019 18:03:47.345 WARNING [Thread-508] org.apache.catalina.servlets.CGIServlet$CGIRunner.sendToLog Received [10] lines on stderr
25-Oct-2019 18:16:36.492 WARNING [Thread-511] org.apache.catalina.servlets.CGIServlet$CGIRunner.sendToLog stderr line: [C:\Users\hayde\AppData\Local\Programs\Python\Python36\lib\site-packages\pymysql\cursors.py:170: Warning: (1366, "Incorrect integer value: '' for column 'year' at row 1")]
25-Oct-2019 18:16:36.493 WARNING [Thread-511] org.apache.catalina.servlets.CGIServlet$CGIRunner.sendToLog stderr line: [  result = self._query(query)]
25-Oct-2019 18:16:36.494 WARNING [Thread-511] org.apache.catalina.servlets.CGIServlet$CGIRunner.sendToLog stderr line: [C:\Users\hayde\AppData\Local\Programs\Python\Python36\lib\site-packages\pymysql\cursors.py:170: Warning: (1366, "Incorrect integer value: '' for column 'width' at row 1")]
25-Oct-2019 18:16:36.494 WARNING [Thread-511] org.apache.catalina.servlets.CGIServlet$CGIRunner.sendToLog stderr line: [  result = self._query(query)]
25-Oct-2019 18:16:36.495 WARNING [Thread-511] org.apache.catalina.servlets.CGIServlet$CGIRunner.sendToLog stderr line: [C:\Users\hayde\AppData\Local\Programs\Python\Python36\lib\site-packages\pymysql\cursors.py:170: Warning: (1366, "Incorrect integer value: '' for column 'height' at row 1")]
25-Oct-2019 18:16:36.495 WARNING [Thread-511] org.apache.catalina.servlets.CGIServlet$CGIRunner.sendToLog stderr line: [  result = self._query(query)]
25-Oct-2019 18:16:36.496 WARNING [Thread-511] org.apache.catalina.servlets.CGIServlet$CGIRunner.sendToLog stderr line: [C:\Users\hayde\AppData\Local\Programs\Python\Python36\lib\site-packages\pymysql\cursors.py:170: Warning: (1366, "Incorrect integer value: 'None' for column 'artist_id' at row 1")]
25-Oct-2019 18:16:36.496 WARNING [Thread-511] org.apache.catalina.servlets.CGIServlet$CGIRunner.sendToLog stderr line: [  result = self._query(query)]
25-Oct-2019 18:16:36.505 WARNING [Thread-511] org.apache.catalina.servlets.CGIServlet$CGIRunner.sendToLog Received [8] lines on stderr
25-Oct-2019 18:16:40.810 WARNING [Thread-512] org.apache.catalina.servlets.CGIServlet$CGIRunner.sendToLog stderr line: [Traceback (most recent call last):]
25-Oct-2019 18:16:40.810 WARNING [Thread-512] org.apache.catalina.servlets.CGIServlet$CGIRunner.sendToLog stderr line: [  File "C:\Users\hayde\Desktop\UCI\Fall 2019\EECS 118\MP2\apache-tomcat-9.0.26\webapps\test\WEB-INF\cgi\project_3_gallery1.py", line 91, in <module>]
25-Oct-2019 18:16:40.810 WARNING [Thread-512] org.apache.catalina.servlets.CGIServlet$CGIRunner.sendToLog stderr line: [    display_artist = "Name: "+str(artist_detail[1])+"<br />Birth Year: "+str(artist_detail[2])+"<br />Coutry: "+str(artist_detail[3])+"<br />Description: "+str(artist_detail[4])]
25-Oct-2019 18:16:40.811 WARNING [Thread-512] org.apache.catalina.servlets.CGIServlet$CGIRunner.sendToLog stderr line: [TypeError: 'NoneType' object is not subscriptable]
25-Oct-2019 18:16:40.818 WARNING [Thread-512] org.apache.catalina.servlets.CGIServlet$CGIRunner.sendToLog Received [4] lines on stderr
25-Oct-2019 18:17:58.602 WARNING [Thread-513] org.apache.catalina.servlets.CGIServlet$CGIRunner.sendToLog stderr line: [Traceback (most recent call last):]
25-Oct-2019 18:17:58.602 WARNING [Thread-513] org.apache.catalina.servlets.CGIServlet$CGIRunner.sendToLog stderr line: [  File "C:\Users\hayde\Desktop\UCI\Fall 2019\EECS 118\MP2\apache-tomcat-9.0.26\webapps\test\WEB-INF\cgi\project_3_gallery1.py", line 91, in <module>]
25-Oct-2019 18:17:58.603 WARNING [Thread-513] org.apache.catalina.servlets.CGIServlet$CGIRunner.sendToLog stderr line: [    display_artist = "Name: "+str(artist_detail[1])+"<br />Birth Year: "+str(artist_detail[2])+"<br />Coutry: "+str(artist_detail[3])+"<br />Description: "+str(artist_detail[4])]
25-Oct-2019 18:17:58.603 WARNING [Thread-513] org.apache.catalina.servlets.CGIServlet$CGIRunner.sendToLog stderr line: [TypeError: 'NoneType' object is not subscriptable]
25-Oct-2019 18:17:58.610 WARNING [Thread-513] org.apache.catalina.servlets.CGIServlet$CGIRunner.sendToLog Received [4] lines on stderr
25-Oct-2019 18:18:02.018 WARNING [Thread-514] org.apache.catalina.servlets.CGIServlet$CGIRunner.sendToLog stderr line: [Traceback (most recent call last):]
25-Oct-2019 18:18:02.019 WARNING [Thread-514] org.apache.catalina.servlets.CGIServlet$CGIRunner.sendToLog stderr line: [  File "C:\Users\hayde\Desktop\UCI\Fall 2019\EECS 118\MP2\apache-tomcat-9.0.26\webapps\test\WEB-INF\cgi\project_3_gallery1.py", line 91, in <module>]
25-Oct-2019 18:18:02.019 WARNING [Thread-514] org.apache.catalina.servlets.CGIServlet$CGIRunner.sendToLog stderr line: [    display_artist = "Name: "+str(artist_detail[1])+"<br />Birth Year: "+str(artist_detail[2])+"<br />Coutry: "+str(artist_detail[3])+"<br />Description: "+str(artist_detail[4])]
25-Oct-2019 18:18:02.020 WARNING [Thread-514] org.apache.catalina.servlets.CGIServlet$CGIRunner.sendToLog stderr line: [TypeError: 'NoneType' object is not subscriptable]
25-Oct-2019 18:18:02.027 WARNING [Thread-514] org.apache.catalina.servlets.CGIServlet$CGIRunner.sendToLog Received [4] lines on stderr
25-Oct-2019 18:18:04.139 WARNING [Thread-515] org.apache.catalina.servlets.CGIServlet$CGIRunner.sendToLog stderr line: [Traceback (most recent call last):]
25-Oct-2019 18:18:04.140 WARNING [Thread-515] org.apache.catalina.servlets.CGIServlet$CGIRunner.sendToLog stderr line: [  File "C:\Users\hayde\Desktop\UCI\Fall 2019\EECS 118\MP2\apache-tomcat-9.0.26\webapps\test\WEB-INF\cgi\project_3.py", line 47, in <module>]
25-Oct-2019 18:18:04.140 WARNING [Thread-515] org.apache.catalina.servlets.CGIServlet$CGIRunner.sendToLog stderr line: [    print(js)]
25-Oct-2019 18:18:04.141 WARNING [Thread-515] org.apache.catalina.servlets.CGIServlet$CGIRunner.sendToLog stderr line: [NameError: name 'js' is not defined]
25-Oct-2019 18:18:04.147 WARNING [Thread-515] org.apache.catalina.servlets.CGIServlet$CGIRunner.sendToLog Received [4] lines on stderr
25-Oct-2019 18:18:06.119 WARNING [Thread-516] org.apache.catalina.servlets.CGIServlet$CGIRunner.sendToLog stderr line: [Traceback (most recent call last):]
25-Oct-2019 18:18:06.119 WARNING [Thread-516] org.apache.catalina.servlets.CGIServlet$CGIRunner.sendToLog stderr line: [  File "C:\Users\hayde\Desktop\UCI\Fall 2019\EECS 118\MP2\apache-tomcat-9.0.26\webapps\test\WEB-INF\cgi\project_3_gallery1.py", line 91, in <module>]
25-Oct-2019 18:18:06.120 WARNING [Thread-516] org.apache.catalina.servlets.CGIServlet$CGIRunner.sendToLog stderr line: [    display_artist = "Name: "+str(artist_detail[1])+"<br />Birth Year: "+str(artist_detail[2])+"<br />Coutry: "+str(artist_detail[3])+"<br />Description: "+str(artist_detail[4])]
25-Oct-2019 18:18:06.120 WARNING [Thread-516] org.apache.catalina.servlets.CGIServlet$CGIRunner.sendToLog stderr line: [TypeError: 'NoneType' object is not subscriptable]
25-Oct-2019 18:18:06.128 WARNING [Thread-516] org.apache.catalina.servlets.CGIServlet$CGIRunner.sendToLog Received [4] lines on stderr
25-Oct-2019 18:18:17.000 WARNING [Thread-518] org.apache.catalina.servlets.CGIServlet$CGIRunner.sendToLog stderr line: [Traceback (most recent call last):]
25-Oct-2019 18:18:17.000 WARNING [Thread-518] org.apache.catalina.servlets.CGIServlet$CGIRunner.sendToLog stderr line: [  File "C:\Users\hayde\Desktop\UCI\Fall 2019\EECS 118\MP2\apache-tomcat-9.0.26\webapps\test\WEB-INF\cgi\project_3_gallery1.py", line 91, in <module>]
25-Oct-2019 18:18:17.001 WARNING [Thread-518] org.apache.catalina.servlets.CGIServlet$CGIRunner.sendToLog stderr line: [    display_artist = "Name: "+str(artist_detail[1])+"<br />Birth Year: "+str(artist_detail[2])+"<br />Coutry: "+str(artist_detail[3])+"<br />Description: "+str(artist_detail[4])]
25-Oct-2019 18:18:17.001 WARNING [Thread-518] org.apache.catalina.servlets.CGIServlet$CGIRunner.sendToLog stderr line: [TypeError: 'NoneType' object is not subscriptable]
25-Oct-2019 18:18:17.009 WARNING [Thread-518] org.apache.catalina.servlets.CGIServlet$CGIRunner.sendToLog Received [4] lines on stderr
25-Oct-2019 18:19:09.404 WARNING [Thread-519] org.apache.catalina.servlets.CGIServlet$CGIRunner.sendToLog stderr line: [Traceback (most recent call last):]
25-Oct-2019 18:19:09.404 WARNING [Thread-519] org.apache.catalina.servlets.CGIServlet$CGIRunner.sendToLog stderr line: [  File "C:\Users\hayde\Desktop\UCI\Fall 2019\EECS 118\MP2\apache-tomcat-9.0.26\webapps\test\WEB-INF\cgi\project_3_gallery1.py", line 91, in <module>]
25-Oct-2019 18:19:09.405 WARNING [Thread-519] org.apache.catalina.servlets.CGIServlet$CGIRunner.sendToLog stderr line: [    display_artist = "Name: "+str(artist_detail[1])+"<br />Birth Year: "+str(artist_detail[2])+"<br />Coutry: "+str(artist_detail[3])+"<br />Description: "+str(artist_detail[4])]
25-Oct-2019 18:19:09.405 WARNING [Thread-519] org.apache.catalina.servlets.CGIServlet$CGIRunner.sendToLog stderr line: [TypeError: 'NoneType' object is not subscriptable]
25-Oct-2019 18:19:09.413 WARNING [Thread-519] org.apache.catalina.servlets.CGIServlet$CGIRunner.sendToLog Received [4] lines on stderr
25-Oct-2019 18:19:17.207 WARNING [Thread-521] org.apache.catalina.servlets.CGIServlet$CGIRunner.sendToLog stderr line: [Traceback (most recent call last):]
25-Oct-2019 18:19:17.207 WARNING [Thread-521] org.apache.catalina.servlets.CGIServlet$CGIRunner.sendToLog stderr line: [  File "C:\Users\hayde\Desktop\UCI\Fall 2019\EECS 118\MP2\apache-tomcat-9.0.26\webapps\test\WEB-INF\cgi\project_3_gallery1.py", line 91, in <module>]
25-Oct-2019 18:19:17.208 WARNING [Thread-521] org.apache.catalina.servlets.CGIServlet$CGIRunner.sendToLog stderr line: [    display_artist = "Name: "+str(artist_detail[1])+"<br />Birth Year: "+str(artist_detail[2])+"<br />Coutry: "+str(artist_detail[3])+"<br />Description: "+str(artist_detail[4])]
25-Oct-2019 18:19:17.208 WARNING [Thread-521] org.apache.catalina.servlets.CGIServlet$CGIRunner.sendToLog stderr line: [TypeError: 'NoneType' object is not subscriptable]
25-Oct-2019 18:19:17.215 WARNING [Thread-521] org.apache.catalina.servlets.CGIServlet$CGIRunner.sendToLog Received [4] lines on stderr
25-Oct-2019 18:19:43.815 WARNING [Thread-523] org.apache.catalina.servlets.CGIServlet$CGIRunner.sendToLog stderr line: [Traceback (most recent call last):]
25-Oct-2019 18:19:43.815 WARNING [Thread-523] org.apache.catalina.servlets.CGIServlet$CGIRunner.sendToLog stderr line: [  File "C:\Users\hayde\Desktop\UCI\Fall 2019\EECS 118\MP2\apache-tomcat-9.0.26\webapps\test\WEB-INF\cgi\project_3_del_img.py", line 22, in <module>]
25-Oct-2019 18:19:43.816 WARNING [Thread-523] org.apache.catalina.servlets.CGIServlet$CGIRunner.sendToLog stderr line: [    cur.execute(query, str(img_detail_id[0]))]
25-Oct-2019 18:19:43.816 WARNING [Thread-523] org.apache.catalina.servlets.CGIServlet$CGIRunner.sendToLog stderr line: [TypeError: 'NoneType' object is not subscriptable]
25-Oct-2019 18:19:43.825 WARNING [Thread-523] org.apache.catalina.servlets.CGIServlet$CGIRunner.sendToLog Received [4] lines on stderr
25-Oct-2019 18:20:12.424 WARNING [Thread-525] org.apache.catalina.servlets.CGIServlet$CGIRunner.sendToLog stderr line: [C:\Users\hayde\AppData\Local\Programs\Python\Python36\lib\site-packages\pymysql\cursors.py:170: Warning: (1366, "Incorrect integer value: '' for column 'year' at row 1")]
25-Oct-2019 18:20:12.425 WARNING [Thread-525] org.apache.catalina.servlets.CGIServlet$CGIRunner.sendToLog stderr line: [  result = self._query(query)]
25-Oct-2019 18:20:12.426 WARNING [Thread-525] org.apache.catalina.servlets.CGIServlet$CGIRunner.sendToLog stderr line: [C:\Users\hayde\AppData\Local\Programs\Python\Python36\lib\site-packages\pymysql\cursors.py:170: Warning: (1366, "Incorrect integer value: '' for column 'width' at row 1")]
25-Oct-2019 18:20:12.427 WARNING [Thread-525] org.apache.catalina.servlets.CGIServlet$CGIRunner.sendToLog stderr line: [  result = self._query(query)]
25-Oct-2019 18:20:12.428 WARNING [Thread-525] org.apache.catalina.servlets.CGIServlet$CGIRunner.sendToLog stderr line: [C:\Users\hayde\AppData\Local\Programs\Python\Python36\lib\site-packages\pymysql\cursors.py:170: Warning: (1366, "Incorrect integer value: '' for column 'height' at row 1")]
25-Oct-2019 18:20:12.428 WARNING [Thread-525] org.apache.catalina.servlets.CGIServlet$CGIRunner.sendToLog stderr line: [  result = self._query(query)]
25-Oct-2019 18:20:12.429 WARNING [Thread-525] org.apache.catalina.servlets.CGIServlet$CGIRunner.sendToLog stderr line: [C:\Users\hayde\AppData\Local\Programs\Python\Python36\lib\site-packages\pymysql\cursors.py:170: Warning: (1366, "Incorrect integer value: 'None' for column 'artist_id' at row 1")]
25-Oct-2019 18:20:12.429 WARNING [Thread-525] org.apache.catalina.servlets.CGIServlet$CGIRunner.sendToLog stderr line: [  result = self._query(query)]
25-Oct-2019 18:20:12.436 WARNING [Thread-525] org.apache.catalina.servlets.CGIServlet$CGIRunner.sendToLog Received [8] lines on stderr
25-Oct-2019 18:20:14.304 WARNING [Thread-526] org.apache.catalina.servlets.CGIServlet$CGIRunner.sendToLog stderr line: [Traceback (most recent call last):]
25-Oct-2019 18:20:14.304 WARNING [Thread-526] org.apache.catalina.servlets.CGIServlet$CGIRunner.sendToLog stderr line: [  File "C:\Users\hayde\Desktop\UCI\Fall 2019\EECS 118\MP2\apache-tomcat-9.0.26\webapps\test\WEB-INF\cgi\project_3_gallery1.py", line 91, in <module>]
25-Oct-2019 18:20:14.305 WARNING [Thread-526] org.apache.catalina.servlets.CGIServlet$CGIRunner.sendToLog stderr line: [    display_artist = "Name: "+str(artist_detail[1])+"<br />Birth Year: "+str(artist_detail[2])+"<br />Coutry: "+str(artist_detail[3])+"<br />Description: "+str(artist_detail[4])]
25-Oct-2019 18:20:14.305 WARNING [Thread-526] org.apache.catalina.servlets.CGIServlet$CGIRunner.sendToLog stderr line: [TypeError: 'NoneType' object is not subscriptable]
25-Oct-2019 18:20:14.313 WARNING [Thread-526] org.apache.catalina.servlets.CGIServlet$CGIRunner.sendToLog Received [4] lines on stderr
25-Oct-2019 18:20:49.299 WARNING [Thread-528] org.apache.catalina.servlets.CGIServlet$CGIRunner.sendToLog stderr line: [C:\Users\hayde\AppData\Local\Programs\Python\Python36\lib\site-packages\pymysql\cursors.py:170: Warning: (1366, "Incorrect integer value: '' for column 'year' at row 1")]
25-Oct-2019 18:20:49.300 WARNING [Thread-528] org.apache.catalina.servlets.CGIServlet$CGIRunner.sendToLog stderr line: [  result = self._query(query)]
25-Oct-2019 18:20:49.301 WARNING [Thread-528] org.apache.catalina.servlets.CGIServlet$CGIRunner.sendToLog stderr line: [C:\Users\hayde\AppData\Local\Programs\Python\Python36\lib\site-packages\pymysql\cursors.py:170: Warning: (1366, "Incorrect integer value: 'None' for column 'artist_id' at row 1")]
25-Oct-2019 18:20:49.301 WARNING [Thread-528] org.apache.catalina.servlets.CGIServlet$CGIRunner.sendToLog stderr line: [  result = self._query(query)]
25-Oct-2019 18:20:49.312 WARNING [Thread-528] org.apache.catalina.servlets.CGIServlet$CGIRunner.sendToLog Received [4] lines on stderr
25-Oct-2019 18:20:50.926 WARNING [Thread-529] org.apache.catalina.servlets.CGIServlet$CGIRunner.sendToLog stderr line: [Traceback (most recent call last):]
25-Oct-2019 18:20:50.926 WARNING [Thread-529] org.apache.catalina.servlets.CGIServlet$CGIRunner.sendToLog stderr line: [  File "C:\Users\hayde\Desktop\UCI\Fall 2019\EECS 118\MP2\apache-tomcat-9.0.26\webapps\test\WEB-INF\cgi\project_3_gallery1.py", line 91, in <module>]
25-Oct-2019 18:20:50.926 WARNING [Thread-529] org.apache.catalina.servlets.CGIServlet$CGIRunner.sendToLog stderr line: [    display_artist = "Name: "+str(artist_detail[1])+"<br />Birth Year: "+str(artist_detail[2])+"<br />Coutry: "+str(artist_detail[3])+"<br />Description: "+str(artist_detail[4])]
25-Oct-2019 18:20:50.927 WARNING [Thread-529] org.apache.catalina.servlets.CGIServlet$CGIRunner.sendToLog stderr line: [TypeError: 'NoneType' object is not subscriptable]
25-Oct-2019 18:20:50.934 WARNING [Thread-529] org.apache.catalina.servlets.CGIServlet$CGIRunner.sendToLog Received [4] lines on stderr
25-Oct-2019 18:22:24.691 WARNING [Thread-531] org.apache.catalina.servlets.CGIServlet$CGIRunner.sendToLog stderr line: [C:\Users\hayde\AppData\Local\Programs\Python\Python36\lib\site-packages\pymysql\cursors.py:170: Warning: (1366, "Incorrect integer value: 'asf' for column 'year' at row 1")]
25-Oct-2019 18:22:24.692 WARNING [Thread-531] org.apache.catalina.servlets.CGIServlet$CGIRunner.sendToLog stderr line: [  result = self._query(query)]
25-Oct-2019 18:22:24.692 WARNING [Thread-531] org.apache.catalina.servlets.CGIServlet$CGIRunner.sendToLog stderr line: [C:\Users\hayde\AppData\Local\Programs\Python\Python36\lib\site-packages\pymysql\cursors.py:170: Warning: (1366, "Incorrect integer value: '' for column 'width' at row 1")]
25-Oct-2019 18:22:24.692 WARNING [Thread-531] org.apache.catalina.servlets.CGIServlet$CGIRunner.sendToLog stderr line: [  result = self._query(query)]
25-Oct-2019 18:22:24.693 WARNING [Thread-531] org.apache.catalina.servlets.CGIServlet$CGIRunner.sendToLog stderr line: [C:\Users\hayde\AppData\Local\Programs\Python\Python36\lib\site-packages\pymysql\cursors.py:170: Warning: (1366, "Incorrect integer value: '' for column 'height' at row 1")]
25-Oct-2019 18:22:24.693 WARNING [Thread-531] org.apache.catalina.servlets.CGIServlet$CGIRunner.sendToLog stderr line: [  result = self._query(query)]
25-Oct-2019 18:22:24.693 WARNING [Thread-531] org.apache.catalina.servlets.CGIServlet$CGIRunner.sendToLog stderr line: [Traceback (most recent call last):]
25-Oct-2019 18:22:24.694 WARNING [Thread-531] org.apache.catalina.servlets.CGIServlet$CGIRunner.sendToLog stderr line: [  File "C:\Users\hayde\Desktop\UCI\Fall 2019\EECS 118\MP2\apache-tomcat-9.0.26\webapps\test\WEB-INF\cgi\project_3_uploaded.py", line 42, in <module>]
25-Oct-2019 18:22:24.694 WARNING [Thread-531] org.apache.catalina.servlets.CGIServlet$CGIRunner.sendToLog stderr line: [    artist_id = artist_id[0]]
25-Oct-2019 18:22:24.694 WARNING [Thread-531] org.apache.catalina.servlets.CGIServlet$CGIRunner.sendToLog stderr line: [TypeError: 'NoneType' object is not subscriptable]
25-Oct-2019 18:22:24.700 WARNING [Thread-531] org.apache.catalina.servlets.CGIServlet$CGIRunner.sendToLog Received [10] lines on stderr
25-Oct-2019 18:22:35.594 WARNING [Thread-532] org.apache.catalina.servlets.CGIServlet$CGIRunner.sendToLog stderr line: [C:\Users\hayde\AppData\Local\Programs\Python\Python36\lib\site-packages\pymysql\cursors.py:170: Warning: (1366, "Incorrect integer value: '' for column 'year' at row 1")]
25-Oct-2019 18:22:35.594 WARNING [Thread-532] org.apache.catalina.servlets.CGIServlet$CGIRunner.sendToLog stderr line: [  result = self._query(query)]
25-Oct-2019 18:22:35.596 WARNING [Thread-532] org.apache.catalina.servlets.CGIServlet$CGIRunner.sendToLog stderr line: [C:\Users\hayde\AppData\Local\Programs\Python\Python36\lib\site-packages\pymysql\cursors.py:170: Warning: (1366, "Incorrect integer value: '' for column 'width' at row 1")]
25-Oct-2019 18:22:35.596 WARNING [Thread-532] org.apache.catalina.servlets.CGIServlet$CGIRunner.sendToLog stderr line: [  result = self._query(query)]
25-Oct-2019 18:22:35.596 WARNING [Thread-532] org.apache.catalina.servlets.CGIServlet$CGIRunner.sendToLog stderr line: [C:\Users\hayde\AppData\Local\Programs\Python\Python36\lib\site-packages\pymysql\cursors.py:170: Warning: (1366, "Incorrect integer value: '' for column 'height' at row 1")]
25-Oct-2019 18:22:35.597 WARNING [Thread-532] org.apache.catalina.servlets.CGIServlet$CGIRunner.sendToLog stderr line: [  result = self._query(query)]
25-Oct-2019 18:22:35.597 WARNING [Thread-532] org.apache.catalina.servlets.CGIServlet$CGIRunner.sendToLog stderr line: [Traceback (most recent call last):]
25-Oct-2019 18:22:35.598 WARNING [Thread-532] org.apache.catalina.servlets.CGIServlet$CGIRunner.sendToLog stderr line: [  File "C:\Users\hayde\Desktop\UCI\Fall 2019\EECS 118\MP2\apache-tomcat-9.0.26\webapps\test\WEB-INF\cgi\project_3_uploaded.py", line 42, in <module>]
25-Oct-2019 18:22:35.598 WARNING [Thread-532] org.apache.catalina.servlets.CGIServlet$CGIRunner.sendToLog stderr line: [    artist_id = artist_id[0]]
25-Oct-2019 18:22:35.598 WARNING [Thread-532] org.apache.catalina.servlets.CGIServlet$CGIRunner.sendToLog stderr line: [TypeError: 'NoneType' object is not subscriptable]
25-Oct-2019 18:22:35.604 WARNING [Thread-532] org.apache.catalina.servlets.CGIServlet$CGIRunner.sendToLog Received [10] lines on stderr
25-Oct-2019 18:26:55.588 WARNING [Thread-533] org.apache.catalina.servlets.CGIServlet$CGIRunner.sendToLog stderr line: [C:\Users\hayde\AppData\Local\Programs\Python\Python36\lib\site-packages\pymysql\cursors.py:170: Warning: (1366, "Incorrect integer value: '' for column 'year' at row 1")]
25-Oct-2019 18:26:55.589 WARNING [Thread-533] org.apache.catalina.servlets.CGIServlet$CGIRunner.sendToLog stderr line: [  result = self._query(query)]
25-Oct-2019 18:26:55.589 WARNING [Thread-533] org.apache.catalina.servlets.CGIServlet$CGIRunner.sendToLog stderr line: [C:\Users\hayde\AppData\Local\Programs\Python\Python36\lib\site-packages\pymysql\cursors.py:170: Warning: (1366, "Incorrect integer value: '' for column 'width' at row 1")]
25-Oct-2019 18:26:55.590 WARNING [Thread-533] org.apache.catalina.servlets.CGIServlet$CGIRunner.sendToLog stderr line: [  result = self._query(query)]
25-Oct-2019 18:26:55.590 WARNING [Thread-533] org.apache.catalina.servlets.CGIServlet$CGIRunner.sendToLog stderr line: [C:\Users\hayde\AppData\Local\Programs\Python\Python36\lib\site-packages\pymysql\cursors.py:170: Warning: (1366, "Incorrect integer value: '' for column 'height' at row 1")]
25-Oct-2019 18:26:55.591 WARNING [Thread-533] org.apache.catalina.servlets.CGIServlet$CGIRunner.sendToLog stderr line: [  result = self._query(query)]
25-Oct-2019 18:26:55.591 WARNING [Thread-533] org.apache.catalina.servlets.CGIServlet$CGIRunner.sendToLog stderr line: [C:\Users\hayde\AppData\Local\Programs\Python\Python36\lib\site-packages\pymysql\cursors.py:170: Warning: (1366, "Incorrect integer value: 'None' for column 'artist_id' at row 1")]
25-Oct-2019 18:26:55.591 WARNING [Thread-533] org.apache.catalina.servlets.CGIServlet$CGIRunner.sendToLog stderr line: [  result = self._query(query)]
25-Oct-2019 18:26:55.599 WARNING [Thread-533] org.apache.catalina.servlets.CGIServlet$CGIRunner.sendToLog Received [8] lines on stderr
25-Oct-2019 18:27:01.598 WARNING [Thread-534] org.apache.catalina.servlets.CGIServlet$CGIRunner.sendToLog stderr line: [Traceback (most recent call last):]
25-Oct-2019 18:27:01.598 WARNING [Thread-534] org.apache.catalina.servlets.CGIServlet$CGIRunner.sendToLog stderr line: [  File "C:\Users\hayde\Desktop\UCI\Fall 2019\EECS 118\MP2\apache-tomcat-9.0.26\webapps\test\WEB-INF\cgi\project_3_gallery1.py", line 89, in <module>]
25-Oct-2019 18:27:01.598 WARNING [Thread-534] org.apache.catalina.servlets.CGIServlet$CGIRunner.sendToLog stderr line: [    display_details = "Year: "+str(detail[2])+"<br />Type: "+str(detail[3])+"<br />Width: "+str(detail[4])+"<br />Height: "+str(detail[5])+"<br />Location: "+str(detail[6])+"<br />Description: "+str(detail[7])]
25-Oct-2019 18:27:01.599 WARNING [Thread-534] org.apache.catalina.servlets.CGIServlet$CGIRunner.sendToLog stderr line: [TypeError: 'NoneType' object is not subscriptable]
25-Oct-2019 18:27:01.606 WARNING [Thread-534] org.apache.catalina.servlets.CGIServlet$CGIRunner.sendToLog Received [4] lines on stderr
25-Oct-2019 18:27:48.426 WARNING [Thread-536] org.apache.catalina.servlets.CGIServlet$CGIRunner.sendToLog stderr line: [C:\Users\hayde\AppData\Local\Programs\Python\Python36\lib\site-packages\pymysql\cursors.py:170: Warning: (1366, "Incorrect integer value: '' for column 'year' at row 1")]
25-Oct-2019 18:27:48.426 WARNING [Thread-536] org.apache.catalina.servlets.CGIServlet$CGIRunner.sendToLog stderr line: [  result = self._query(query)]
25-Oct-2019 18:27:48.427 WARNING [Thread-536] org.apache.catalina.servlets.CGIServlet$CGIRunner.sendToLog stderr line: [C:\Users\hayde\AppData\Local\Programs\Python\Python36\lib\site-packages\pymysql\cursors.py:170: Warning: (1366, "Incorrect integer value: '' for column 'width' at row 1")]
25-Oct-2019 18:27:48.427 WARNING [Thread-536] org.apache.catalina.servlets.CGIServlet$CGIRunner.sendToLog stderr line: [  result = self._query(query)]
25-Oct-2019 18:27:48.427 WARNING [Thread-536] org.apache.catalina.servlets.CGIServlet$CGIRunner.sendToLog stderr line: [C:\Users\hayde\AppData\Local\Programs\Python\Python36\lib\site-packages\pymysql\cursors.py:170: Warning: (1366, "Incorrect integer value: '' for column 'height' at row 1")]
25-Oct-2019 18:27:48.427 WARNING [Thread-536] org.apache.catalina.servlets.CGIServlet$CGIRunner.sendToLog stderr line: [  result = self._query(query)]
25-Oct-2019 18:27:48.428 WARNING [Thread-536] org.apache.catalina.servlets.CGIServlet$CGIRunner.sendToLog stderr line: [C:\Users\hayde\AppData\Local\Programs\Python\Python36\lib\site-packages\pymysql\cursors.py:170: Warning: (1366, "Incorrect integer value: 'None' for column 'artist_id' at row 1")]
25-Oct-2019 18:27:48.428 WARNING [Thread-536] org.apache.catalina.servlets.CGIServlet$CGIRunner.sendToLog stderr line: [  result = self._query(query)]
25-Oct-2019 18:27:48.435 WARNING [Thread-536] org.apache.catalina.servlets.CGIServlet$CGIRunner.sendToLog Received [8] lines on stderr
25-Oct-2019 18:28:50.155 WARNING [Thread-539] org.apache.catalina.servlets.CGIServlet$CGIRunner.sendToLog stderr line: [C:\Users\hayde\AppData\Local\Programs\Python\Python36\lib\site-packages\pymysql\cursors.py:170: Warning: (1366, "Incorrect integer value: '' for column 'year' at row 1")]
25-Oct-2019 18:28:50.156 WARNING [Thread-539] org.apache.catalina.servlets.CGIServlet$CGIRunner.sendToLog stderr line: [  result = self._query(query)]
25-Oct-2019 18:28:50.156 WARNING [Thread-539] org.apache.catalina.servlets.CGIServlet$CGIRunner.sendToLog stderr line: [C:\Users\hayde\AppData\Local\Programs\Python\Python36\lib\site-packages\pymysql\cursors.py:170: Warning: (1366, "Incorrect integer value: '' for column 'width' at row 1")]
25-Oct-2019 18:28:50.156 WARNING [Thread-539] org.apache.catalina.servlets.CGIServlet$CGIRunner.sendToLog stderr line: [  result = self._query(query)]
25-Oct-2019 18:28:50.157 WARNING [Thread-539] org.apache.catalina.servlets.CGIServlet$CGIRunner.sendToLog stderr line: [C:\Users\hayde\AppData\Local\Programs\Python\Python36\lib\site-packages\pymysql\cursors.py:170: Warning: (1366, "Incorrect integer value: '' for column 'height' at row 1")]
25-Oct-2019 18:28:50.157 WARNING [Thread-539] org.apache.catalina.servlets.CGIServlet$CGIRunner.sendToLog stderr line: [  result = self._query(query)]
25-Oct-2019 18:28:50.157 WARNING [Thread-539] org.apache.catalina.servlets.CGIServlet$CGIRunner.sendToLog stderr line: [C:\Users\hayde\AppData\Local\Programs\Python\Python36\lib\site-packages\pymysql\cursors.py:170: Warning: (1366, "Incorrect integer value: 'None' for column 'artist_id' at row 1")]
25-Oct-2019 18:28:50.158 WARNING [Thread-539] org.apache.catalina.servlets.CGIServlet$CGIRunner.sendToLog stderr line: [  result = self._query(query)]
25-Oct-2019 18:28:50.164 WARNING [Thread-539] org.apache.catalina.servlets.CGIServlet$CGIRunner.sendToLog Received [8] lines on stderr
25-Oct-2019 18:28:52.094 WARNING [Thread-540] org.apache.catalina.servlets.CGIServlet$CGIRunner.sendToLog stderr line: [Traceback (most recent call last):]
25-Oct-2019 18:28:52.094 WARNING [Thread-540] org.apache.catalina.servlets.CGIServlet$CGIRunner.sendToLog stderr line: [  File "C:\Users\hayde\Desktop\UCI\Fall 2019\EECS 118\MP2\apache-tomcat-9.0.26\webapps\test\WEB-INF\cgi\project_3_gallery1.py", line 91, in <module>]
25-Oct-2019 18:28:52.094 WARNING [Thread-540] org.apache.catalina.servlets.CGIServlet$CGIRunner.sendToLog stderr line: [    display_artist = "Name: "+str(artist_detail[1])+"<br />Birth Year: "+str(artist_detail[2])+"<br />Coutry: "+str(artist_detail[3])+"<br />Description: "+str(artist_detail[4])]
25-Oct-2019 18:28:52.095 WARNING [Thread-540] org.apache.catalina.servlets.CGIServlet$CGIRunner.sendToLog stderr line: [TypeError: 'NoneType' object is not subscriptable]
25-Oct-2019 18:28:52.102 WARNING [Thread-540] org.apache.catalina.servlets.CGIServlet$CGIRunner.sendToLog Received [4] lines on stderr
25-Oct-2019 18:29:50.670 WARNING [Thread-541] org.apache.catalina.servlets.CGIServlet$CGIRunner.sendToLog stderr line: [Traceback (most recent call last):]
25-Oct-2019 18:29:50.670 WARNING [Thread-541] org.apache.catalina.servlets.CGIServlet$CGIRunner.sendToLog stderr line: [  File "C:\Users\hayde\Desktop\UCI\Fall 2019\EECS 118\MP2\apache-tomcat-9.0.26\webapps\test\WEB-INF\cgi\project_3_create_artist.py", line 18, in <module>]
25-Oct-2019 18:29:50.671 WARNING [Thread-541] org.apache.catalina.servlets.CGIServlet$CGIRunner.sendToLog stderr line: [    display_upload += "<input type='hidden' name='upload_img' value='"+form.getvalue('upload_img')+"'>" + "<input type='submit' value='Add'/></form>"]
25-Oct-2019 18:29:50.671 WARNING [Thread-541] org.apache.catalina.servlets.CGIServlet$CGIRunner.sendToLog stderr line: [TypeError: must be str, not NoneType]
25-Oct-2019 18:29:50.678 WARNING [Thread-541] org.apache.catalina.servlets.CGIServlet$CGIRunner.sendToLog Received [4] lines on stderr
25-Oct-2019 18:30:25.491 WARNING [Thread-542] org.apache.catalina.servlets.CGIServlet$CGIRunner.sendToLog stderr line: [Traceback (most recent call last):]
25-Oct-2019 18:30:25.492 WARNING [Thread-542] org.apache.catalina.servlets.CGIServlet$CGIRunner.sendToLog stderr line: [  File "C:\Users\hayde\Desktop\UCI\Fall 2019\EECS 118\MP2\apache-tomcat-9.0.26\webapps\test\WEB-INF\cgi\project_3_gallery1.py", line 91, in <module>]
25-Oct-2019 18:30:25.492 WARNING [Thread-542] org.apache.catalina.servlets.CGIServlet$CGIRunner.sendToLog stderr line: [    display_artist = "Name: "+str(artist_detail[1])+"<br />Birth Year: "+str(artist_detail[2])+"<br />Coutry: "+str(artist_detail[3])+"<br />Description: "+str(artist_detail[4])]
25-Oct-2019 18:30:25.493 WARNING [Thread-542] org.apache.catalina.servlets.CGIServlet$CGIRunner.sendToLog stderr line: [TypeError: 'NoneType' object is not subscriptable]
25-Oct-2019 18:30:25.501 WARNING [Thread-542] org.apache.catalina.servlets.CGIServlet$CGIRunner.sendToLog Received [4] lines on stderr
25-Oct-2019 18:30:26.520 WARNING [Thread-543] org.apache.catalina.servlets.CGIServlet$CGIRunner.sendToLog stderr line: [Traceback (most recent call last):]
25-Oct-2019 18:30:26.520 WARNING [Thread-543] org.apache.catalina.servlets.CGIServlet$CGIRunner.sendToLog stderr line: [  File "C:\Users\hayde\Desktop\UCI\Fall 2019\EECS 118\MP2\apache-tomcat-9.0.26\webapps\test\WEB-INF\cgi\project_3_create_artist.py", line 18, in <module>]
25-Oct-2019 18:30:26.520 WARNING [Thread-543] org.apache.catalina.servlets.CGIServlet$CGIRunner.sendToLog stderr line: [    display_upload += "<input type='hidden' name='upload_img' value='"+form.getvalue('upload_img')+"'>" + "<input type='submit' value='Add'/></form>"]
25-Oct-2019 18:30:26.521 WARNING [Thread-543] org.apache.catalina.servlets.CGIServlet$CGIRunner.sendToLog stderr line: [TypeError: must be str, not NoneType]
25-Oct-2019 18:30:26.528 WARNING [Thread-543] org.apache.catalina.servlets.CGIServlet$CGIRunner.sendToLog Received [4] lines on stderr
25-Oct-2019 18:33:27.494 WARNING [Thread-544] org.apache.catalina.servlets.CGIServlet$CGIRunner.sendToLog stderr line: [  File "C:\Users\hayde\Desktop\UCI\Fall 2019\EECS 118\MP2\apache-tomcat-9.0.26\webapps\test\WEB-INF\cgi\project_3_gallery1.py", line 83]
25-Oct-2019 18:33:27.494 WARNING [Thread-544] org.apache.catalina.servlets.CGIServlet$CGIRunner.sendToLog stderr line: [    if artist_id[0] = 0:]
25-Oct-2019 18:33:27.495 WARNING [Thread-544] org.apache.catalina.servlets.CGIServlet$CGIRunner.sendToLog stderr line: [                    ^]
25-Oct-2019 18:33:27.495 WARNING [Thread-544] org.apache.catalina.servlets.CGIServlet$CGIRunner.sendToLog stderr line: [SyntaxError: invalid syntax]
25-Oct-2019 18:33:27.497 WARNING [Thread-544] org.apache.catalina.servlets.CGIServlet$CGIRunner.sendToLog Received [4] lines on stderr
25-Oct-2019 18:33:49.042 WARNING [Thread-545] org.apache.catalina.servlets.CGIServlet$CGIRunner.sendToLog stderr line: [  File "C:\Users\hayde\Desktop\UCI\Fall 2019\EECS 118\MP2\apache-tomcat-9.0.26\webapps\test\WEB-INF\cgi\project_3_gallery1.py", line 83]
25-Oct-2019 18:33:49.042 WARNING [Thread-545] org.apache.catalina.servlets.CGIServlet$CGIRunner.sendToLog stderr line: [    if artist_id[0] = '0':]
25-Oct-2019 18:33:49.042 WARNING [Thread-545] org.apache.catalina.servlets.CGIServlet$CGIRunner.sendToLog stderr line: [                    ^]
25-Oct-2019 18:33:49.043 WARNING [Thread-545] org.apache.catalina.servlets.CGIServlet$CGIRunner.sendToLog stderr line: [SyntaxError: invalid syntax]
25-Oct-2019 18:33:49.045 WARNING [Thread-545] org.apache.catalina.servlets.CGIServlet$CGIRunner.sendToLog Received [4] lines on stderr
25-Oct-2019 18:33:59.523 WARNING [Thread-546] org.apache.catalina.servlets.CGIServlet$CGIRunner.sendToLog stderr line: [  File "C:\Users\hayde\Desktop\UCI\Fall 2019\EECS 118\MP2\apache-tomcat-9.0.26\webapps\test\WEB-INF\cgi\project_3_gallery1.py", line 83]
25-Oct-2019 18:33:59.523 WARNING [Thread-546] org.apache.catalina.servlets.CGIServlet$CGIRunner.sendToLog stderr line: [    if artist_id[0] = '0':]
25-Oct-2019 18:33:59.524 WARNING [Thread-546] org.apache.catalina.servlets.CGIServlet$CGIRunner.sendToLog stderr line: [                    ^]
25-Oct-2019 18:33:59.524 WARNING [Thread-546] org.apache.catalina.servlets.CGIServlet$CGIRunner.sendToLog stderr line: [SyntaxError: invalid syntax]
25-Oct-2019 18:33:59.527 WARNING [Thread-546] org.apache.catalina.servlets.CGIServlet$CGIRunner.sendToLog Received [4] lines on stderr
25-Oct-2019 18:36:07.179 WARNING [Thread-547] org.apache.catalina.servlets.CGIServlet$CGIRunner.sendToLog stderr line: [  File "C:\Users\hayde\Desktop\UCI\Fall 2019\EECS 118\MP2\apache-tomcat-9.0.26\webapps\test\WEB-INF\cgi\project_3_gallery1.py", line 83]
25-Oct-2019 18:36:07.179 WARNING [Thread-547] org.apache.catalina.servlets.CGIServlet$CGIRunner.sendToLog stderr line: [    if artist_id[0] = '0':]
25-Oct-2019 18:36:07.180 WARNING [Thread-547] org.apache.catalina.servlets.CGIServlet$CGIRunner.sendToLog stderr line: [                    ^]
25-Oct-2019 18:36:07.180 WARNING [Thread-547] org.apache.catalina.servlets.CGIServlet$CGIRunner.sendToLog stderr line: [SyntaxError: invalid syntax]
25-Oct-2019 18:36:07.182 WARNING [Thread-547] org.apache.catalina.servlets.CGIServlet$CGIRunner.sendToLog Received [4] lines on stderr
25-Oct-2019 18:36:13.012 WARNING [Thread-548] org.apache.catalina.servlets.CGIServlet$CGIRunner.sendToLog stderr line: [  File "C:\Users\hayde\Desktop\UCI\Fall 2019\EECS 118\MP2\apache-tomcat-9.0.26\webapps\test\WEB-INF\cgi\project_3_gallery1.py", line 83]
25-Oct-2019 18:36:13.012 WARNING [Thread-548] org.apache.catalina.servlets.CGIServlet$CGIRunner.sendToLog stderr line: [    if artist_id[0] = 0:]
25-Oct-2019 18:36:13.013 WARNING [Thread-548] org.apache.catalina.servlets.CGIServlet$CGIRunner.sendToLog stderr line: [                    ^]
25-Oct-2019 18:36:13.014 WARNING [Thread-548] org.apache.catalina.servlets.CGIServlet$CGIRunner.sendToLog stderr line: [SyntaxError: invalid syntax]
25-Oct-2019 18:36:13.015 WARNING [Thread-548] org.apache.catalina.servlets.CGIServlet$CGIRunner.sendToLog Received [4] lines on stderr
25-Oct-2019 18:36:37.519 WARNING [Thread-549] org.apache.catalina.servlets.CGIServlet$CGIRunner.sendToLog stderr line: [Traceback (most recent call last):]
25-Oct-2019 18:36:37.520 WARNING [Thread-549] org.apache.catalina.servlets.CGIServlet$CGIRunner.sendToLog stderr line: [  File "C:\Users\hayde\Desktop\UCI\Fall 2019\EECS 118\MP2\apache-tomcat-9.0.26\webapps\test\WEB-INF\cgi\project_3_gallery1.py", line 89, in <module>]
25-Oct-2019 18:36:37.520 WARNING [Thread-549] org.apache.catalina.servlets.CGIServlet$CGIRunner.sendToLog stderr line: [    display_artist = "Name: "+str(artist_detail[1])+"<br />Birth Year: "+str(artist_detail[2])+"<br />Coutry: "+str(artist_detail[3])+"<br />Description: "+str(artist_detail[4])]
25-Oct-2019 18:36:37.521 WARNING [Thread-549] org.apache.catalina.servlets.CGIServlet$CGIRunner.sendToLog stderr line: [TypeError: 'NoneType' object is not subscriptable]
25-Oct-2019 18:36:37.528 WARNING [Thread-549] org.apache.catalina.servlets.CGIServlet$CGIRunner.sendToLog Received [4] lines on stderr
25-Oct-2019 18:38:34.014 WARNING [Thread-550] org.apache.catalina.servlets.CGIServlet$CGIRunner.sendToLog stderr line: [  File "C:\Users\hayde\Desktop\UCI\Fall 2019\EECS 118\MP2\apache-tomcat-9.0.26\webapps\test\WEB-INF\cgi\project_3_gallery1.py", line 83]
25-Oct-2019 18:38:34.014 WARNING [Thread-550] org.apache.catalina.servlets.CGIServlet$CGIRunner.sendToLog stderr line: [    if artist_id[0] = 0:]
25-Oct-2019 18:38:34.015 WARNING [Thread-550] org.apache.catalina.servlets.CGIServlet$CGIRunner.sendToLog stderr line: [                    ^]
25-Oct-2019 18:38:34.015 WARNING [Thread-550] org.apache.catalina.servlets.CGIServlet$CGIRunner.sendToLog stderr line: [SyntaxError: invalid syntax]
25-Oct-2019 18:38:34.017 WARNING [Thread-550] org.apache.catalina.servlets.CGIServlet$CGIRunner.sendToLog Received [4] lines on stderr
25-Oct-2019 18:40:22.113 WARNING [Thread-551] org.apache.catalina.servlets.CGIServlet$CGIRunner.sendToLog stderr line: [  File "C:\Users\hayde\Desktop\UCI\Fall 2019\EECS 118\MP2\apache-tomcat-9.0.26\webapps\test\WEB-INF\cgi\project_3_gallery1.py", line 83]
25-Oct-2019 18:40:22.114 WARNING [Thread-551] org.apache.catalina.servlets.CGIServlet$CGIRunner.sendToLog stderr line: [    if artist_id[0] = '0':]
25-Oct-2019 18:40:22.114 WARNING [Thread-551] org.apache.catalina.servlets.CGIServlet$CGIRunner.sendToLog stderr line: [                    ^]
25-Oct-2019 18:40:22.114 WARNING [Thread-551] org.apache.catalina.servlets.CGIServlet$CGIRunner.sendToLog stderr line: [SyntaxError: invalid syntax]
25-Oct-2019 18:40:22.116 WARNING [Thread-551] org.apache.catalina.servlets.CGIServlet$CGIRunner.sendToLog Received [4] lines on stderr
25-Oct-2019 18:41:23.438 WARNING [Thread-552] org.apache.catalina.servlets.CGIServlet$CGIRunner.sendToLog stderr line: [Traceback (most recent call last):]
25-Oct-2019 18:41:23.438 WARNING [Thread-552] org.apache.catalina.servlets.CGIServlet$CGIRunner.sendToLog stderr line: [  File "C:\Users\hayde\Desktop\UCI\Fall 2019\EECS 118\MP2\apache-tomcat-9.0.26\webapps\test\WEB-INF\cgi\project_3_gallery1.py", line 90, in <module>]
25-Oct-2019 18:41:23.438 WARNING [Thread-552] org.apache.catalina.servlets.CGIServlet$CGIRunner.sendToLog stderr line: [    display_artist = "Name: "+str(artist_detail[1])+"<br />Birth Year: "+str(artist_detail[2])+"<br />Coutry: "+str(artist_detail[3])+"<br />Description: "+str(artist_detail[4])]
25-Oct-2019 18:41:23.439 WARNING [Thread-552] org.apache.catalina.servlets.CGIServlet$CGIRunner.sendToLog stderr line: [TypeError: 'NoneType' object is not subscriptable]
25-Oct-2019 18:41:23.447 WARNING [Thread-552] org.apache.catalina.servlets.CGIServlet$CGIRunner.sendToLog Received [4] lines on stderr
25-Oct-2019 18:41:58.067 WARNING [Thread-553] org.apache.catalina.servlets.CGIServlet$CGIRunner.sendToLog stderr line: [Traceback (most recent call last):]
25-Oct-2019 18:41:58.067 WARNING [Thread-553] org.apache.catalina.servlets.CGIServlet$CGIRunner.sendToLog stderr line: [  File "C:\Users\hayde\Desktop\UCI\Fall 2019\EECS 118\MP2\apache-tomcat-9.0.26\webapps\test\WEB-INF\cgi\project_3_create_artist.py", line 19, in <module>]
25-Oct-2019 18:41:58.068 WARNING [Thread-553] org.apache.catalina.servlets.CGIServlet$CGIRunner.sendToLog stderr line: [    display_upload += "<input type='hidden' name='upload_img' value='"+form.getvalue('upload_img')+"'>" + "<input type='submit' value='Add'/></form>"]
25-Oct-2019 18:41:58.068 WARNING [Thread-553] org.apache.catalina.servlets.CGIServlet$CGIRunner.sendToLog stderr line: [TypeError: must be str, not NoneType]
25-Oct-2019 18:41:58.075 WARNING [Thread-553] org.apache.catalina.servlets.CGIServlet$CGIRunner.sendToLog Received [4] lines on stderr
25-Oct-2019 18:42:03.011 WARNING [Thread-555] org.apache.catalina.servlets.CGIServlet$CGIRunner.sendToLog stderr line: [Traceback (most recent call last):]
25-Oct-2019 18:42:03.011 WARNING [Thread-555] org.apache.catalina.servlets.CGIServlet$CGIRunner.sendToLog stderr line: [  File "C:\Users\hayde\Desktop\UCI\Fall 2019\EECS 118\MP2\apache-tomcat-9.0.26\webapps\test\WEB-INF\cgi\project_3.py", line 47, in <module>]
25-Oct-2019 18:42:03.012 WARNING [Thread-555] org.apache.catalina.servlets.CGIServlet$CGIRunner.sendToLog stderr line: [    print(js)]
25-Oct-2019 18:42:03.012 WARNING [Thread-555] org.apache.catalina.servlets.CGIServlet$CGIRunner.sendToLog stderr line: [NameError: name 'js' is not defined]
25-Oct-2019 18:42:03.020 WARNING [Thread-555] org.apache.catalina.servlets.CGIServlet$CGIRunner.sendToLog Received [4] lines on stderr
25-Oct-2019 18:42:05.016 WARNING [Thread-556] org.apache.catalina.servlets.CGIServlet$CGIRunner.sendToLog stderr line: [Traceback (most recent call last):]
25-Oct-2019 18:42:05.017 WARNING [Thread-556] org.apache.catalina.servlets.CGIServlet$CGIRunner.sendToLog stderr line: [  File "C:\Users\hayde\Desktop\UCI\Fall 2019\EECS 118\MP2\apache-tomcat-9.0.26\webapps\test\WEB-INF\cgi\project_3_gallery1.py", line 90, in <module>]
25-Oct-2019 18:42:05.017 WARNING [Thread-556] org.apache.catalina.servlets.CGIServlet$CGIRunner.sendToLog stderr line: [    display_artist = "Name: "+str(artist_detail[1])+"<br />Birth Year: "+str(artist_detail[2])+"<br />Coutry: "+str(artist_detail[3])+"<br />Description: "+str(artist_detail[4])]
25-Oct-2019 18:42:05.017 WARNING [Thread-556] org.apache.catalina.servlets.CGIServlet$CGIRunner.sendToLog stderr line: [TypeError: 'NoneType' object is not subscriptable]
25-Oct-2019 18:42:05.025 WARNING [Thread-556] org.apache.catalina.servlets.CGIServlet$CGIRunner.sendToLog Received [4] lines on stderr
25-Oct-2019 18:44:00.587 WARNING [Thread-559] org.apache.catalina.servlets.CGIServlet$CGIRunner.sendToLog stderr line: [Traceback (most recent call last):]
25-Oct-2019 18:44:00.587 WARNING [Thread-559] org.apache.catalina.servlets.CGIServlet$CGIRunner.sendToLog stderr line: [  File "C:\Users\hayde\Desktop\UCI\Fall 2019\EECS 118\MP2\apache-tomcat-9.0.26\webapps\test\WEB-INF\cgi\project_3.py", line 47, in <module>]
25-Oct-2019 18:44:00.588 WARNING [Thread-559] org.apache.catalina.servlets.CGIServlet$CGIRunner.sendToLog stderr line: [    print(js)]
25-Oct-2019 18:44:00.588 WARNING [Thread-559] org.apache.catalina.servlets.CGIServlet$CGIRunner.sendToLog stderr line: [NameError: name 'js' is not defined]
25-Oct-2019 18:44:00.595 WARNING [Thread-559] org.apache.catalina.servlets.CGIServlet$CGIRunner.sendToLog Received [4] lines on stderr
